<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_friend_add.proto

namespace GPBMetadata\Plugin;

class HaiFriendAdd
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aac020a1b706c7567696e2f6861695f667269656e645f6164642e70726f" .
            "746f1206706c7567696e22480a13486169467269656e6441646452657175" .
            "65737412140a0c736974655f757365725f6964180120012809121b0a1366" .
            "7269656e645f736974655f757365725f696418022001280922160a144861" .
            "69467269656e64416464526573706f6e736532570a13486169467269656e" .
            "644164645365727669636512400a03616464121b2e706c7567696e2e4861" .
            "69467269656e64416464526571756573741a1c2e706c7567696e2e486169" .
            "467269656e64416464526573706f6e736542420a17636f6d2e616b617869" .
            "6e2e70726f746f2e706c7567696e4211486169467269656e644164645072" .
            "6f746fca0213416b6178696e5c50726f746f5c506c7567696e620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

