<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_friend_phone.proto

namespace GPBMetadata\Plugin;

class HaiFriendPhone
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac7020a1d706c7567696e2f6861695f667269656e645f70686f6e652e70" .
            "726f746f1206706c7567696e222d0a15486169467269656e6450686f6e65" .
            "5265717565737412140a0c736974655f757365725f696418012001280922" .
            "400a16486169467269656e6450686f6e65526573706f6e736512140a0c63" .
            "6f756e7472795f636f646518012001280912100a0870686f6e655f696418" .
            "0220012809325f0a15486169467269656e6450686f6e6553657276696365" .
            "12460a0570686f6e65121d2e706c7567696e2e486169467269656e645068" .
            "6f6e65526571756573741a1e2e706c7567696e2e486169467269656e6450" .
            "686f6e65526573706f6e736542440a17636f6d2e616b6178696e2e70726f" .
            "746f2e706c7567696e4213486169467269656e6450686f6e6550726f746f" .
            "ca0213416b6178696e5c50726f746f5c506c7567696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

