<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_friend_apply.proto

namespace GPBMetadata\Plugin;

class HaiFriendApply
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad2020a1d706c7567696e2f6861695f667269656e645f6170706c792e70" .
            "726f746f1206706c7567696e22600a15486169467269656e644170706c79" .
            "5265717565737412140a0c736974655f757365725f696418012001280912" .
            "1b0a13667269656e645f736974655f757365725f69641802200128091214" .
            "0a0c6170706c795f726561736f6e18032001280922180a16486169467269" .
            "656e644170706c79526573706f6e7365325f0a15486169467269656e6441" .
            "70706c795365727669636512460a056170706c79121d2e706c7567696e2e" .
            "486169467269656e644170706c79526571756573741a1e2e706c7567696e" .
            "2e486169467269656e644170706c79526573706f6e736542440a17636f6d" .
            "2e616b6178696e2e70726f746f2e706c7567696e4213486169467269656e" .
            "644170706c7950726f746fca0213416b6178696e5c50726f746f5c506c75" .
            "67696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

