<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_friend_add.proto

namespace GPBMetadata\Plugin;

class HaiFriendAdd
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a91020a1b706c7567696e2f6861695f667269656e645f6164642e70726f" .
            "746f1206706c7567696e222d0a13486169467269656e6441646452657175" .
            "65737412160a0e736974655f667269656e645f696418012001280922160a" .
            "14486169467269656e64416464526573706f6e736532570a134861694672" .
            "69656e644164645365727669636512400a03616464121b2e706c7567696e" .
            "2e486169467269656e64416464526571756573741a1c2e706c7567696e2e" .
            "486169467269656e64416464526573706f6e736542420a17636f6d2e616b" .
            "6178696e2e70726f746f2e706c7567696e4211486169467269656e644164" .
            "6450726f746fca0213416b6178696e5c50726f746f5c506c7567696e6206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

