<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_friend_relations.proto

namespace GPBMetadata\Plugin;

class HaiFriendRelations
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aeb020a21706c7567696e2f6861695f667269656e645f72656c6174696f" .
            "6e732e70726f746f1206706c7567696e222c0a19486169467269656e6452" .
            "656c6174696f6e7352657175657374120f0a07757365725f696418012003" .
            "2809224d0a1a486169467269656e6452656c6174696f6e73526573706f6e" .
            "7365122f0a0c757365725f70726f66696c6518012003280b32192e636f72" .
            "652e5573657252656c6174696f6e50726f66696c65326f0a194861694672" .
            "69656e6452656c6174696f6e735365727669636512520a0972656c617469" .
            "6f6e7312212e706c7567696e2e486169467269656e6452656c6174696f6e" .
            "73526571756573741a222e706c7567696e2e486169467269656e6452656c" .
            "6174696f6e73526573706f6e736542480a17636f6d2e616b6178696e2e70" .
            "726f746f2e706c7567696e4217486169467269656e6452656c6174696f6e" .
            "7350726f746fca0213416b6178696e5c50726f746f5c506c7567696e6206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

