<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_nonmembers.proto

namespace GPBMetadata\Plugin;

class HaiGroupNonmembers
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Group::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac2030a21706c7567696e2f6861695f67726f75705f6e6f6e6d656d6265" .
            "72732e70726f746f1206706c7567696e226b0a1948616947726f75704e6f" .
            "6e6d656d626572735265717565737412140a0c736974655f757365725f69" .
            "6418012001280912100a0867726f75705f696418022001280912130a0b70" .
            "6167655f6e756d62657218032001280512110a09706167655f73697a6518" .
            "042001280522640a1a48616947726f75704e6f6e6d656d62657273526573" .
            "706f6e7365122e0a0c67726f75705f6d656d62657218012003280b32182e" .
            "636f72652e47726f75704d656d62657250726f66696c6512160a0e706167" .
            "655f746f74616c5f6e756d18022001280532700a1948616947726f75704e" .
            "6f6e6d656d626572735365727669636512530a0a6e6f6e6d656d62657273" .
            "12212e706c7567696e2e48616947726f75704e6f6e6d656d626572735265" .
            "71756573741a222e706c7567696e2e48616947726f75704e6f6e6d656d62" .
            "657273526573706f6e736542480a17636f6d2e616b6178696e2e70726f74" .
            "6f2e706c7567696e421748616947726f75704e6f6e6d656d626572735072" .
            "6f746fca0213416b6178696e5c50726f746f5c506c7567696e620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

