<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_checkMember.proto

namespace GPBMetadata\Plugin;

class HaiGroupCheckMember
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af8020a22706c7567696e2f6861695f67726f75705f636865636b4d656d" .
            "6265722e70726f746f1206706c7567696e22440a1a48616947726f757043" .
            "6865636b4d656d6265725265717565737412100a0867726f75705f696418" .
            "012001280912140a0c736974655f757365725f6964180220032809223b0a" .
            "1b48616947726f7570436865636b4d656d626572526573706f6e7365121c" .
            "0a146d656d626572735f736974655f757365725f69641801200328093274" .
            "0a1a48616947726f7570436865636b4d656d626572536572766963651256" .
            "0a0b636865636b4d656d62657212222e706c7567696e2e48616947726f75" .
            "70436865636b4d656d626572526571756573741a232e706c7567696e2e48" .
            "616947726f7570436865636b4d656d626572526573706f6e736542490a17" .
            "636f6d2e616b6178696e2e70726f746f2e706c7567696e42184861694772" .
            "6f7570436865636b4d656d62657250726f746fca0213416b6178696e5c50" .
            "726f746f5c506c7567696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

