<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_update.proto

namespace GPBMetadata\Plugin;

class HaiGroupUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Group::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac1020a1d706c7567696e2f6861695f67726f75705f7570646174652e70" .
            "726f746f1206706c7567696e224e0a1548616947726f7570557064617465" .
            "5265717565737412100a0867726f75705f696418012001280912230a0770" .
            "726f66696c6518022001280b32122e636f72652e47726f757050726f6669" .
            "6c6522180a1648616947726f7570557064617465526573706f6e73653260" .
            "0a1548616947726f75705570646174655365727669636512470a06757064" .
            "617465121d2e706c7567696e2e48616947726f7570557064617465526571" .
            "756573741a1e2e706c7567696e2e48616947726f75705570646174655265" .
            "73706f6e736542440a17636f6d2e616b6178696e2e70726f746f2e706c75" .
            "67696e421348616947726f757055706461746550726f746fca0213416b61" .
            "78696e5c50726f746f5c506c7567696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

