<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_addMember.proto

namespace GPBMetadata\Plugin;

class HaiGroupAddMember
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad1020a20706c7567696e2f6861695f67726f75705f6164644d656d6265" .
            "722e70726f746f1206706c7567696e22490a1848616947726f7570416464" .
            "4d656d6265725265717565737412100a0867726f75705f69641801200128" .
            "09121b0a136d656d6265725f736974655f757365725f6964180220032809" .
            "221b0a1948616947726f75704164644d656d626572526573706f6e736532" .
            "6c0a1848616947726f75704164644d656d6265725365727669636512500a" .
            "096164644d656d62657212202e706c7567696e2e48616947726f75704164" .
            "644d656d626572526571756573741a212e706c7567696e2e48616947726f" .
            "75704164644d656d626572526573706f6e736542470a17636f6d2e616b61" .
            "78696e2e70726f746f2e706c7567696e421648616947726f75704164644d" .
            "656d62657250726f746fca0213416b6178696e5c50726f746f5c506c7567" .
            "696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

