<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_message_proxy.proto

namespace GPBMetadata\Plugin;

class HaiMessageProxy
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Core::initOnce();
        \GPBMetadata\Site\ImCtsMessage::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0acc020a1e706c7567696e2f6861695f6d6573736167655f70726f78792e" .
            "70726f746f1206706c7567696e1a19736974652f696d5f6374735f6d6573" .
            "736167652e70726f746f22460a164861694d65737361676550726f787952" .
            "657175657374122c0a0970726f78795f6d736718012001280b32192e7369" .
            "74652e496d4374734d6573736167655265717565737422190a174861694d" .
            "65737361676550726f7879526573706f6e736532550a164861694d657373" .
            "61676550726f787953657276696365123b0a0570726f7879121e2e706c75" .
            "67696e2e4861694d65737361676550726f7879526571756573741a122e63" .
            "6f72652e4e6f6e65526573706f6e736542450a17636f6d2e616b6178696e" .
            "2e70726f746f2e706c7567696e42144861694d65737361676550726f7879" .
            "50726f746fca0213416b6178696e5c50726f746f5c506c7567696e620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

