<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_plugin_profile.proto

namespace GPBMetadata\Plugin;

class HaiPluginProfile
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Plugin::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aca020a1f706c7567696e2f6861695f706c7567696e5f70726f66696c65" .
            "2e70726f746f1206706c7567696e222c0a17486169506c7567696e50726f" .
            "66696c655265717565737412110a09706c7567696e5f6964180120012809" .
            "22380a18486169506c7567696e50726f66696c65526573706f6e7365121c" .
            "0a06706c7567696e18012001280b320c2e636f72652e506c7567696e3267" .
            "0a17486169506c7567696e50726f66696c6553657276696365124c0a0770" .
            "726f66696c65121f2e706c7567696e2e486169506c7567696e50726f6669" .
            "6c65526571756573741a202e706c7567696e2e486169506c7567696e5072" .
            "6f66696c65526573706f6e736542460a17636f6d2e616b6178696e2e7072" .
            "6f746f2e706c7567696e4215486169506c7567696e50726f66696c655072" .
            "6f746fca0213416b6178696e5c50726f746f5c506c7567696e620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

