<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_plugin_delete.proto

namespace GPBMetadata\Plugin;

class HaiPluginDelete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa4020a1e706c7567696e2f6861695f706c7567696e5f64656c6574652e" .
            "70726f746f1206706c7567696e222b0a16486169506c7567696e44656c65" .
            "74655265717565737412110a09706c7567696e5f69641801200128092219" .
            "0a17486169506c7567696e44656c657465526573706f6e736532630a1648" .
            "6169506c7567696e44656c6574655365727669636512490a0664656c6574" .
            "65121e2e706c7567696e2e486169506c7567696e44656c65746552657175" .
            "6573741a1f2e706c7567696e2e486169506c7567696e44656c6574655265" .
            "73706f6e736542450a17636f6d2e616b6178696e2e70726f746f2e706c75" .
            "67696e4214486169506c7567696e44656c65746550726f746fca0213416b" .
            "6178696e5c50726f746f5c506c7567696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

