<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_push_notices.proto

namespace GPBMetadata\Plugin;

class HaiPushNotices
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac1020a1d706c7567696e2f6861695f707573685f6e6f74696365732e70" .
            "726f746f1206706c7567696e224d0a15486169507573684e6f7469636573" .
            "5265717565737412100a087375627469746c65180120012809120f0a0763" .
            "6f6e74656e7418022001280912110a09707573685f676f746f1803200128" .
            "0922180a16486169507573684e6f7469636573526573706f6e736532610a" .
            "15486169507573684e6f74696365735365727669636512480a076e6f7469" .
            "636573121d2e706c7567696e2e486169507573684e6f7469636573526571" .
            "756573741a1e2e706c7567696e2e486169507573684e6f74696365735265" .
            "73706f6e736542440a17636f6d2e616b6178696e2e70726f746f2e706c75" .
            "67696e4213486169507573684e6f746963657350726f746fca0213416b61" .
            "78696e5c50726f746f5c506c7567696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

