<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_plugin_update.proto

namespace GPBMetadata\Plugin;

class HaiPluginUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Plugin::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaf020a1e706c7567696e2f6861695f706c7567696e5f7570646174652e" .
            "70726f746f1206706c7567696e22360a16486169506c7567696e55706461" .
            "746552657175657374121c0a06706c7567696e18012001280b320c2e636f" .
            "72652e506c7567696e22190a17486169506c7567696e5570646174655265" .
            "73706f6e736532630a16486169506c7567696e5570646174655365727669" .
            "636512490a06757064617465121e2e706c7567696e2e486169506c756769" .
            "6e557064617465526571756573741a1f2e706c7567696e2e486169506c75" .
            "67696e557064617465526573706f6e736542450a17636f6d2e616b617869" .
            "6e2e70726f746f2e706c7567696e4214486169506c7567696e5570646174" .
            "6550726f746fca0213416b6178696e5c50726f746f5c506c7567696e6206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

