<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_session_profile.proto

namespace GPBMetadata\Plugin;

class HaiSessionProfile
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aed020a20706c7567696e2f6861695f73657373696f6e5f70726f66696c" .
            "652e70726f746f1206706c7567696e223e0a1848616953657373696f6e50" .
            "726f66696c655265717565737412220a1a6261736536345f736166655f75" .
            "726c5f73657373696f6e5f696418012001280922440a1948616953657373" .
            "696f6e50726f66696c65526573706f6e736512270a0c757365725f70726f" .
            "66696c6518012001280b32112e636f72652e5573657250726f66696c6532" .
            "6a0a1848616953657373696f6e50726f66696c6553657276696365124e0a" .
            "0770726f66696c6512202e706c7567696e2e48616953657373696f6e5072" .
            "6f66696c65526571756573741a212e706c7567696e2e4861695365737369" .
            "6f6e50726f66696c65526573706f6e736542470a17636f6d2e616b617869" .
            "6e2e70726f746f2e706c7567696e421648616953657373696f6e50726f66" .
            "696c6550726f746fca0213416b6178696e5c50726f746f5c506c7567696e" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

