<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_groups.proto

namespace GPBMetadata\Plugin;

class HaiUserGroups
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Group::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afe020a1c706c7567696e2f6861695f757365725f67726f7570732e7072" .
            "6f746f1206706c7567696e22540a144861695573657247726f7570735265" .
            "717565737412140a0c736974655f757365725f696418012001280912130a" .
            "0b706167655f6e756d62657218032001280512110a09706167655f73697a" .
            "6518042001280522540a154861695573657247726f757073526573706f6e" .
            "736512230a0770726f66696c6518012003280b32122e636f72652e47726f" .
            "757050726f66696c6512160a0e706167655f746f74616c5f6e756d180220" .
            "012805325d0a144861695573657247726f7570735365727669636512450a" .
            "0667726f757073121c2e706c7567696e2e4861695573657247726f757073" .
            "526571756573741a1d2e706c7567696e2e4861695573657247726f757073" .
            "526573706f6e736542430a17636f6d2e616b6178696e2e70726f746f2e70" .
            "6c7567696e42124861695573657247726f75707350726f746fca0213416b" .
            "6178696e5c50726f746f5c506c7567696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

