<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_phone.proto

namespace GPBMetadata\Plugin;

class HaiUserPhone
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab9020a1b706c7567696e2f6861695f757365725f70686f6e652e70726f" .
            "746f1206706c7567696e222b0a134861695573657250686f6e6552657175" .
            "65737412140a0c736974655f757365725f6964180120012809223e0a1448" .
            "61695573657250686f6e65526573706f6e736512140a0c636f756e747279" .
            "5f636f646518012001280912100a0870686f6e655f696418022001280932" .
            "590a134861695573657250686f6e655365727669636512420a0570686f6e" .
            "65121b2e706c7567696e2e4861695573657250686f6e6552657175657374" .
            "1a1c2e706c7567696e2e4861695573657250686f6e65526573706f6e7365" .
            "42420a17636f6d2e616b6178696e2e70726f746f2e706c7567696e421148" .
            "61695573657250686f6e6550726f746fca0213416b6178696e5c50726f74" .
            "6f5c506c7567696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

