<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_friends.proto

namespace GPBMetadata\Plugin;

class HaiUserFriends
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8b030a1d706c7567696e2f6861695f757365725f667269656e64732e70" .
            "726f746f1206706c7567696e22550a1548616955736572467269656e6473" .
            "5265717565737412140a0c736974655f757365725f696418012001280912" .
            "130a0b706167655f6e756d62657218032001280512110a09706167655f73" .
            "697a65180420012805225a0a1648616955736572467269656e6473526573" .
            "706f6e736512280a0770726f66696c6518012003280b32172e636f72652e" .
            "53696d706c655573657250726f66696c6512160a0e706167655f746f7461" .
            "6c5f6e756d18022001280532610a1548616955736572467269656e647353" .
            "65727669636512480a07667269656e6473121d2e706c7567696e2e486169" .
            "55736572467269656e6473526571756573741a1e2e706c7567696e2e4861" .
            "6955736572467269656e6473526573706f6e736542440a17636f6d2e616b" .
            "6178696e2e70726f746f2e706c7567696e42134861695573657246726965" .
            "6e647350726f746fca0213416b6178696e5c50726f746f5c506c7567696e" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

