<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_uic_create.proto

namespace GPBMetadata\Plugin;

class HaiUicCreate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abc020a1b706c7567696e2f6861695f7569635f6372656174652e70726f" .
            "746f1206706c7567696e223d0a1348616955696343726561746552657175" .
            "65737412120a0a7569635f6e756d62657218012001280512120a0a756963" .
            "5f6c656e677468180220012805222e0a1448616955696343726561746552" .
            "6573706f6e736512160a0e737563636573735f6e756d6265721801200128" .
            "05325a0a134861695569634372656174655365727669636512430a066372" .
            "65617465121b2e706c7567696e2e48616955696343726561746552657175" .
            "6573741a1c2e706c7567696e2e486169556963437265617465526573706f" .
            "6e736542420a17636f6d2e616b6178696e2e70726f746f2e706c7567696e" .
            "421148616955696343726561746550726f746fca0213416b6178696e5c50" .
            "726f746f5c506c7567696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

