<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_avatar.proto

namespace GPBMetadata\Plugin;

class HaiUserAvatar
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab0020a1c706c7567696e2f6861695f757365725f6176617461722e7072" .
            "6f746f1206706c7567696e222c0a14486169557365724176617461725265" .
            "717565737412140a0c736974655f757365725f6964180120012809222e0a" .
            "1548616955736572417661746172526573706f6e736512150a0d70686f74" .
            "6f5f636f6e74656e7418022001280c325d0a144861695573657241766174" .
            "61725365727669636512450a06617661746172121c2e706c7567696e2e48" .
            "616955736572417661746172526571756573741a1d2e706c7567696e2e48" .
            "616955736572417661746172526573706f6e736542430a17636f6d2e616b" .
            "6178696e2e70726f746f2e706c7567696e42124861695573657241766174" .
            "617250726f746fca0213416b6178696e5c50726f746f5c506c7567696e62" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

