<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/im_cts_message.proto

namespace Akaxin\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 
 */
class ImCtsMessageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *消息类型
     *
     * 
     */
    private $type = 0;
    /**
     *二人文本消息
     *
     * 
     */
    private $text = null;
    /**
     *二人加密文本消息
     *
     * 
     */
    private $secretText = null;
    /**
     *群文本消息
     *
     * 
     */
    private $groupText = null;
    /**
     *群加密消息
     *
     * 
     */
    private $groupSecretText = null;
    /**
     *二人图片消息
     *
     * 
     */
    private $image = null;
    /**
     *二人加密图片消息
     *
     * 
     */
    private $secretImage = null;
    /**
     *群图片消息
     *
     * 
     */
    private $groupImage = null;
    /**
     *群图片加密消息
     *
     * 
     */
    private $groupSecretImage = null;
    /**
     *二人语音
     *
     * 
     */
    private $voice = null;
    /**
     *二人加密语音
     *
     * 
     */
    private $secretVoice = null;
    /**
     *群语音
     *
     * 
     */
    private $groupVoice = null;
    /**
     *群加密语音
     *
     * 
     */
    private $groupSecretVoice = null;
    /**
     *v0.4.3 版本未使用
     *
     * 
     */
    private $u2Map = null;
    /**
     *加密地图消息
     *
     * 
     */
    private $u2SecretMap = null;
    /**
     *群地图
     *
     * 
     */
    private $groupMap = null;
    /**
     *群加密地图
     *
     * 
     */
    private $groupSecretMap = null;
    /**
     *通知消息
     *
     * 
     */
    private $u2MsgNotice = null;
    /**
     *群消息通知
     *
     * 
     */
    private $groupMsgNotice = null;
    /**
     *召回消息
     *
     * 
     */
    private $u2Recall = null;
    /**
     *群组召回消息
     *
     * 
     */
    private $groupRecall = null;
    /**
     *web消息
     *
     * 
     */
    private $u2Web = null;
    /**
     *群组web消息
     *
     * 
     */
    private $groupWeb = null;
    /**
     *web通知消息
     *
     * 
     */
    private $u2WebNotice = null;
    /**
     *群组web通知消息
     *
     * 
     */
    private $groupWebNotice = null;

    public function __construct() {
        \GPBMetadata\Site\ImCtsMessage::initOnce();
        parent::__construct();
    }

    /**
     *消息类型
     *
     * 
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *消息类型
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Akaxin\Proto\Core\MsgType::class);
        $this->type = $var;

        return $this;
    }

    /**
     *二人文本消息
     *
     * 
     * @return \Akaxin\Proto\Core\MsgText
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     *二人文本消息
     *
     * 
     * @param \Akaxin\Proto\Core\MsgText $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\MsgText::class);
        $this->text = $var;

        return $this;
    }

    /**
     *二人加密文本消息
     *
     * 
     * @return \Akaxin\Proto\Core\MsgSecretText
     */
    public function getSecretText()
    {
        return $this->secretText;
    }

    /**
     *二人加密文本消息
     *
     * 
     * @param \Akaxin\Proto\Core\MsgSecretText $var
     * @return $this
     */
    public function setSecretText($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\MsgSecretText::class);
        $this->secretText = $var;

        return $this;
    }

    /**
     *群文本消息
     *
     * 
     * @return \Akaxin\Proto\Core\GroupText
     */
    public function getGroupText()
    {
        return $this->groupText;
    }

    /**
     *群文本消息
     *
     * 
     * @param \Akaxin\Proto\Core\GroupText $var
     * @return $this
     */
    public function setGroupText($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\GroupText::class);
        $this->groupText = $var;

        return $this;
    }

    /**
     *群加密消息
     *
     * 
     * @return \Akaxin\Proto\Core\GroupSecretText
     */
    public function getGroupSecretText()
    {
        return $this->groupSecretText;
    }

    /**
     *群加密消息
     *
     * 
     * @param \Akaxin\Proto\Core\GroupSecretText $var
     * @return $this
     */
    public function setGroupSecretText($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\GroupSecretText::class);
        $this->groupSecretText = $var;

        return $this;
    }

    /**
     *二人图片消息
     *
     * 
     * @return \Akaxin\Proto\Core\MsgImage
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     *二人图片消息
     *
     * 
     * @param \Akaxin\Proto\Core\MsgImage $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\MsgImage::class);
        $this->image = $var;

        return $this;
    }

    /**
     *二人加密图片消息
     *
     * 
     * @return \Akaxin\Proto\Core\MsgSecretImage
     */
    public function getSecretImage()
    {
        return $this->secretImage;
    }

    /**
     *二人加密图片消息
     *
     * 
     * @param \Akaxin\Proto\Core\MsgSecretImage $var
     * @return $this
     */
    public function setSecretImage($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\MsgSecretImage::class);
        $this->secretImage = $var;

        return $this;
    }

    /**
     *群图片消息
     *
     * 
     * @return \Akaxin\Proto\Core\GroupImage
     */
    public function getGroupImage()
    {
        return $this->groupImage;
    }

    /**
     *群图片消息
     *
     * 
     * @param \Akaxin\Proto\Core\GroupImage $var
     * @return $this
     */
    public function setGroupImage($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\GroupImage::class);
        $this->groupImage = $var;

        return $this;
    }

    /**
     *群图片加密消息
     *
     * 
     * @return \Akaxin\Proto\Core\GroupSecretImage
     */
    public function getGroupSecretImage()
    {
        return $this->groupSecretImage;
    }

    /**
     *群图片加密消息
     *
     * 
     * @param \Akaxin\Proto\Core\GroupSecretImage $var
     * @return $this
     */
    public function setGroupSecretImage($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\GroupSecretImage::class);
        $this->groupSecretImage = $var;

        return $this;
    }

    /**
     *二人语音
     *
     * 
     * @return \Akaxin\Proto\Core\MsgVoice
     */
    public function getVoice()
    {
        return $this->voice;
    }

    /**
     *二人语音
     *
     * 
     * @param \Akaxin\Proto\Core\MsgVoice $var
     * @return $this
     */
    public function setVoice($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\MsgVoice::class);
        $this->voice = $var;

        return $this;
    }

    /**
     *二人加密语音
     *
     * 
     * @return \Akaxin\Proto\Core\MsgSecretVoice
     */
    public function getSecretVoice()
    {
        return $this->secretVoice;
    }

    /**
     *二人加密语音
     *
     * 
     * @param \Akaxin\Proto\Core\MsgSecretVoice $var
     * @return $this
     */
    public function setSecretVoice($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\MsgSecretVoice::class);
        $this->secretVoice = $var;

        return $this;
    }

    /**
     *群语音
     *
     * 
     * @return \Akaxin\Proto\Core\GroupVoice
     */
    public function getGroupVoice()
    {
        return $this->groupVoice;
    }

    /**
     *群语音
     *
     * 
     * @param \Akaxin\Proto\Core\GroupVoice $var
     * @return $this
     */
    public function setGroupVoice($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\GroupVoice::class);
        $this->groupVoice = $var;

        return $this;
    }

    /**
     *群加密语音
     *
     * 
     * @return \Akaxin\Proto\Core\GroupSecretVoice
     */
    public function getGroupSecretVoice()
    {
        return $this->groupSecretVoice;
    }

    /**
     *群加密语音
     *
     * 
     * @param \Akaxin\Proto\Core\GroupSecretVoice $var
     * @return $this
     */
    public function setGroupSecretVoice($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\GroupSecretVoice::class);
        $this->groupSecretVoice = $var;

        return $this;
    }

    /**
     *v0.4.3 版本未使用
     *
     * 
     * @return \Akaxin\Proto\Core\U2Map
     */
    public function getU2Map()
    {
        return $this->u2Map;
    }

    /**
     *v0.4.3 版本未使用
     *
     * 
     * @param \Akaxin\Proto\Core\U2Map $var
     * @return $this
     */
    public function setU2Map($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\U2Map::class);
        $this->u2Map = $var;

        return $this;
    }

    /**
     *加密地图消息
     *
     * 
     * @return \Akaxin\Proto\Core\U2SecretMap
     */
    public function getU2SecretMap()
    {
        return $this->u2SecretMap;
    }

    /**
     *加密地图消息
     *
     * 
     * @param \Akaxin\Proto\Core\U2SecretMap $var
     * @return $this
     */
    public function setU2SecretMap($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\U2SecretMap::class);
        $this->u2SecretMap = $var;

        return $this;
    }

    /**
     *群地图
     *
     * 
     * @return \Akaxin\Proto\Core\GroupMap
     */
    public function getGroupMap()
    {
        return $this->groupMap;
    }

    /**
     *群地图
     *
     * 
     * @param \Akaxin\Proto\Core\GroupMap $var
     * @return $this
     */
    public function setGroupMap($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\GroupMap::class);
        $this->groupMap = $var;

        return $this;
    }

    /**
     *群加密地图
     *
     * 
     * @return \Akaxin\Proto\Core\GroupSecretMap
     */
    public function getGroupSecretMap()
    {
        return $this->groupSecretMap;
    }

    /**
     *群加密地图
     *
     * 
     * @param \Akaxin\Proto\Core\GroupSecretMap $var
     * @return $this
     */
    public function setGroupSecretMap($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\GroupSecretMap::class);
        $this->groupSecretMap = $var;

        return $this;
    }

    /**
     *通知消息
     *
     * 
     * @return \Akaxin\Proto\Core\U2MsgNotice
     */
    public function getU2MsgNotice()
    {
        return $this->u2MsgNotice;
    }

    /**
     *通知消息
     *
     * 
     * @param \Akaxin\Proto\Core\U2MsgNotice $var
     * @return $this
     */
    public function setU2MsgNotice($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\U2MsgNotice::class);
        $this->u2MsgNotice = $var;

        return $this;
    }

    /**
     *群消息通知
     *
     * 
     * @return \Akaxin\Proto\Core\GroupMsgNotice
     */
    public function getGroupMsgNotice()
    {
        return $this->groupMsgNotice;
    }

    /**
     *群消息通知
     *
     * 
     * @param \Akaxin\Proto\Core\GroupMsgNotice $var
     * @return $this
     */
    public function setGroupMsgNotice($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\GroupMsgNotice::class);
        $this->groupMsgNotice = $var;

        return $this;
    }

    /**
     *召回消息
     *
     * 
     * @return \Akaxin\Proto\Core\U2Recall
     */
    public function getU2Recall()
    {
        return $this->u2Recall;
    }

    /**
     *召回消息
     *
     * 
     * @param \Akaxin\Proto\Core\U2Recall $var
     * @return $this
     */
    public function setU2Recall($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\U2Recall::class);
        $this->u2Recall = $var;

        return $this;
    }

    /**
     *群组召回消息
     *
     * 
     * @return \Akaxin\Proto\Core\GroupRecall
     */
    public function getGroupRecall()
    {
        return $this->groupRecall;
    }

    /**
     *群组召回消息
     *
     * 
     * @param \Akaxin\Proto\Core\GroupRecall $var
     * @return $this
     */
    public function setGroupRecall($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\GroupRecall::class);
        $this->groupRecall = $var;

        return $this;
    }

    /**
     *web消息
     *
     * 
     * @return \Akaxin\Proto\Core\U2Web
     */
    public function getU2Web()
    {
        return $this->u2Web;
    }

    /**
     *web消息
     *
     * 
     * @param \Akaxin\Proto\Core\U2Web $var
     * @return $this
     */
    public function setU2Web($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\U2Web::class);
        $this->u2Web = $var;

        return $this;
    }

    /**
     *群组web消息
     *
     * 
     * @return \Akaxin\Proto\Core\GroupWeb
     */
    public function getGroupWeb()
    {
        return $this->groupWeb;
    }

    /**
     *群组web消息
     *
     * 
     * @param \Akaxin\Proto\Core\GroupWeb $var
     * @return $this
     */
    public function setGroupWeb($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\GroupWeb::class);
        $this->groupWeb = $var;

        return $this;
    }

    /**
     *web通知消息
     *
     * 
     * @return \Akaxin\Proto\Core\U2WebNotice
     */
    public function getU2WebNotice()
    {
        return $this->u2WebNotice;
    }

    /**
     *web通知消息
     *
     * 
     * @param \Akaxin\Proto\Core\U2WebNotice $var
     * @return $this
     */
    public function setU2WebNotice($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\U2WebNotice::class);
        $this->u2WebNotice = $var;

        return $this;
    }

    /**
     *群组web通知消息
     *
     * 
     * @return \Akaxin\Proto\Core\GroupWebNotice
     */
    public function getGroupWebNotice()
    {
        return $this->groupWebNotice;
    }

    /**
     *群组web通知消息
     *
     * 
     * @param \Akaxin\Proto\Core\GroupWebNotice $var
     * @return $this
     */
    public function setGroupWebNotice($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\GroupWebNotice::class);
        $this->groupWebNotice = $var;

        return $this;
    }

}

