<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/client.proto

namespace GPBMetadata\Core;

class Client
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac5010a11636f72652f636c69656e742e70726f746f1204636f72652a68" .
            "0a0a436c69656e7454797065120a0a06554e4b4e4f57100012070a03494f" .
            "531001120b0a07414e44524f4944100212120a0e414e44524f49445f5849" .
            "414f4d49100312120a0e414e44524f49445f485541574549100412100a0c" .
            "414e44524f49445f4f50504f100542380a15636f6d2e616b6178696e2e70" .
            "726f746f2e636f7265420b436c69656e7450726f746fca0211416b617869" .
            "6e5c50726f746f5c436f7265620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

