<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/device.proto

namespace GPBMetadata\Core;

class Device
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab9020a11636f72652f6465766963652e70726f746f1204636f7265226a" .
            "0a0d44657669636550726f66696c6512110a096465766963655f69641801" .
            "2001280912130a0b6465766963655f6e616d6518022001280912180a1075" .
            "7365725f6465766963655f7075626b18032001280912170a0f6c6173745f" .
            "6c6f67696e5f74696d6518042001280322700a1353696d706c6544657669" .
            "636550726f66696c6512110a096465766963655f69641801200128091213" .
            "0a0b6465766963655f6e616d6518022001280912180a10757365725f6465" .
            "766963655f7075626b18032001280912170a0f6c6173745f6c6f67696e5f" .
            "74696d6518042001280342380a15636f6d2e616b6178696e2e70726f746f" .
            "2e636f7265420b44657669636550726f746fca0211416b6178696e5c5072" .
            "6f746f5c436f7265620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

