<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/file.proto

namespace GPBMetadata\Core;

class File
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afe020a0f636f72652f66696c652e70726f746f1204636f726522500a04" .
            "46696c65120f0a0766696c655f696418012001280912140a0c66696c655f" .
            "636f6e74656e7418022001280c12210a0966696c655f7479706518032001" .
            "280e320e2e636f72652e46696c655479706522470a0846696c6544657363" .
            "120e0a066c656e677468180120012805120d0a0577696474681802200128" .
            "05120e0a06686569676874180320012805120c0a0473697a651804200128" .
            "052a89010a0846696c655479706512100a0c554e4b4e4f574e5f46494c45" .
            "100012110a0d555345525f504f525452414954100112110a0d4d45535341" .
            "47455f494d414745100212110a0d4d4553534147455f564f494345100312" .
            "120a0e47524f55505f504f5254524149541004120f0a0b534954455f504c" .
            "5547494e1005120d0a09534954455f49434f4e100642360a15636f6d2e61" .
            "6b6178696e2e70726f746f2e636f7265420946696c6550726f746fca0211" .
            "416b6178696e5c50726f746f5c436f7265620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

