<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/phone.proto

namespace GPBMetadata\Core;

class Phone
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac6010a10636f72652f70686f6e652e70726f746f1204636f72652a6b0a" .
            "06564354797065120b0a07554e49464945441000120f0a0b50484f4e455f" .
            "4c4f47494e100112120a0e50484f4e455f5245414c4e414d45100212120a" .
            "0e50484f4e455f52454749535445521003121b0a1750484f4e455f524547" .
            "49535445525f464f525f53495445100442370a15636f6d2e616b6178696e" .
            "2e70726f746f2e636f7265420a50686f6e6550726f746fca0211416b6178" .
            "696e5c50726f746f5c436f7265620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

