<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/user.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 
 */
class ApplyUserProfile extends \Google\Protobuf\Internal\Message
{
    /**
     * 
     */
    private $applyUser = null;
    /**
     * 
     */
    private $applyReason = '';

    public function __construct() {
        \GPBMetadata\Core\User::initOnce();
        parent::__construct();
    }

    /**
     * 
     * @return \Akaxin\Proto\Core\UserProfile
     */
    public function getApplyUser()
    {
        return $this->applyUser;
    }

    /**
     * 
     * @param \Akaxin\Proto\Core\UserProfile $var
     * @return $this
     */
    public function setApplyUser($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\UserProfile::class);
        $this->applyUser = $var;

        return $this;
    }

    /**
     * 
     * @return string
     */
    public function getApplyReason()
    {
        return $this->applyReason;
    }

    /**
     * 
     * @param string $var
     * @return $this
     */
    public function setApplyReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->applyReason = $var;

        return $this;
    }

}

