<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/client.proto

namespace Akaxin\Proto\Core;

/**
 *客户端类型
 *
 * Protobuf enum <code>Core\ClientType</code>
 */
class ClientType
{
    /**
     *未知客户端
     *
     * Generated from protobuf enum <code>UNKNOW = 0;</code>
     */
    const UNKNOW = 0;
    /**
     *IOS客户端
     *
     * Generated from protobuf enum <code>IOS = 1;</code>
     */
    const IOS = 1;
    /**
     *ANDROID客户端
     *
     * Generated from protobuf enum <code>ANDROID = 2;</code>
     */
    const ANDROID = 2;
    /**
     *小米客户端
     *
     * Generated from protobuf enum <code>ANDROID_XIAOMI = 3;</code>
     */
    const ANDROID_XIAOMI = 3;
    /**
     *华为客户端
     *
     * Generated from protobuf enum <code>ANDROID_HUAWEI = 4;</code>
     */
    const ANDROID_HUAWEI = 4;
    /**
     *OPPO客户端
     *
     * Generated from protobuf enum <code>ANDROID_OPPO = 5;</code>
     */
    const ANDROID_OPPO = 5;
}

