<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/file.proto

namespace Akaxin\Proto\Core;

/**
 * Protobuf enum <code>Core\FileType</code>
 */
class FileType
{
    /**
     * 未知的文件类型类型
     *
     * Generated from protobuf enum <code>UNKNOWN_FILE = 0;</code>
     */
    const UNKNOWN_FILE = 0;
    /**
     *用户，群头像
     *
     * Generated from protobuf enum <code>USER_PORTRAIT = 1;</code>
     */
    const USER_PORTRAIT = 1;
    /**
     * 个人消息，群图片消息
     *
     * Generated from protobuf enum <code>MESSAGE_IMAGE = 2;</code>
     */
    const MESSAGE_IMAGE = 2;
    /**
     * 个人，群语音消息
     *
     * Generated from protobuf enum <code>MESSAGE_VOICE = 3;</code>
     */
    const MESSAGE_VOICE = 3;
    /**
     *群头像
     *
     * Generated from protobuf enum <code>GROUP_PORTRAIT = 4;</code>
     */
    const GROUP_PORTRAIT = 4;
    /**
     * 站点扩展图片存放位置
     *
     * Generated from protobuf enum <code>SITE_PLUGIN = 5;</code>
     */
    const SITE_PLUGIN = 5;
    /**
     *站点本身相关图片，例如站点logo
     *
     * Generated from protobuf enum <code>SITE_ICON = 6;</code>
     */
    const SITE_ICON = 6;
}

