<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *群组WEB通知：内嵌web通知消息
 *
 * Generated from protobuf message <code>core.GroupWebNotice</code>
 */
class GroupWebNotice extends \Google\Protobuf\Internal\Message
{
    /**
     *消息ID
     *
     * Generated from protobuf field <code>string msg_id = 1;</code>
     */
    private $msg_id = '';
    /**
     *from
     *
     * Generated from protobuf field <code>string site_user_id = 2;</code>
     */
    private $site_user_id = '';
    /**
     *群ID(to)
     *
     * Generated from protobuf field <code>string site_group_id = 3;</code>
     */
    private $site_group_id = '';
    /**
     *统一使用web消息需要的代码内容
     *
     * Generated from protobuf field <code>string web_code = 4;</code>
     */
    private $web_code = '';
    /**
     *消息时间
     *
     * Generated from protobuf field <code>int64 time = 5;</code>
     */
    private $time = 0;

    public function __construct() {
        \GPBMetadata\Core\Core::initOnce();
        parent::__construct();
    }

    /**
     *消息ID
     *
     * Generated from protobuf field <code>string msg_id = 1;</code>
     * @return string
     */
    public function getMsgId()
    {
        return $this->msg_id;
    }

    /**
     *消息ID
     *
     * Generated from protobuf field <code>string msg_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg_id = $var;

        return $this;
    }

    /**
     *from
     *
     * Generated from protobuf field <code>string site_user_id = 2;</code>
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->site_user_id;
    }

    /**
     *from
     *
     * Generated from protobuf field <code>string site_user_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_user_id = $var;

        return $this;
    }

    /**
     *群ID(to)
     *
     * Generated from protobuf field <code>string site_group_id = 3;</code>
     * @return string
     */
    public function getSiteGroupId()
    {
        return $this->site_group_id;
    }

    /**
     *群ID(to)
     *
     * Generated from protobuf field <code>string site_group_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_group_id = $var;

        return $this;
    }

    /**
     *统一使用web消息需要的代码内容
     *
     * Generated from protobuf field <code>string web_code = 4;</code>
     * @return string
     */
    public function getWebCode()
    {
        return $this->web_code;
    }

    /**
     *统一使用web消息需要的代码内容
     *
     * Generated from protobuf field <code>string web_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setWebCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->web_code = $var;

        return $this;
    }

    /**
     *消息时间
     *
     * Generated from protobuf field <code>int64 time = 5;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     *消息时间
     *
     * Generated from protobuf field <code>int64 time = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

}

