<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *加密群地理位置消息
 *
 * 
 */
class GroupSecretMap extends \Google\Protobuf\Internal\Message
{
    /**
     *消息id
     *
     * 
     */
    private $msg_id = '';
    /**
     *from
     *
     * 
     */
    private $site_user_id = '';
    /**
     *to（群ID）
     *
     * 
     */
    private $site_group_id = '';
    /**
     *加密经度
     *
     * 
     */
    private $base64_lng = '';
    /**
     *加密纬度
     *
     * 
     */
    private $base64_lat = '';
    /**
     *base64的加密key，用于AES加密使用
     *
     * 
     */
    private $base64_ts_key = '';
    /**
     *接受者的设备ID
     *
     * 
     */
    private $to_device_id = '';
    /**
     *消息时间，单位ms
     *
     * 
     */
    private $time = 0;

    public function __construct() {
        \GPBMetadata\Core\Core::initOnce();
        parent::__construct();
    }

    /**
     *消息id
     *
     * 
     * @return string
     */
    public function getMsgId()
    {
        return $this->msg_id;
    }

    /**
     *消息id
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg_id = $var;

        return $this;
    }

    /**
     *from
     *
     * 
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->site_user_id;
    }

    /**
     *from
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_user_id = $var;

        return $this;
    }

    /**
     *to（群ID）
     *
     * 
     * @return string
     */
    public function getSiteGroupId()
    {
        return $this->site_group_id;
    }

    /**
     *to（群ID）
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_group_id = $var;

        return $this;
    }

    /**
     *加密经度
     *
     * 
     * @return string
     */
    public function getBase64Lng()
    {
        return $this->base64_lng;
    }

    /**
     *加密经度
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setBase64Lng($var)
    {
        GPBUtil::checkString($var, True);
        $this->base64_lng = $var;

        return $this;
    }

    /**
     *加密纬度
     *
     * 
     * @return string
     */
    public function getBase64Lat()
    {
        return $this->base64_lat;
    }

    /**
     *加密纬度
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setBase64Lat($var)
    {
        GPBUtil::checkString($var, True);
        $this->base64_lat = $var;

        return $this;
    }

    /**
     *base64的加密key，用于AES加密使用
     *
     * 
     * @return string
     */
    public function getBase64TsKey()
    {
        return $this->base64_ts_key;
    }

    /**
     *base64的加密key，用于AES加密使用
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setBase64TsKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->base64_ts_key = $var;

        return $this;
    }

    /**
     *接受者的设备ID
     *
     * 
     * @return string
     */
    public function getToDeviceId()
    {
        return $this->to_device_id;
    }

    /**
     *接受者的设备ID
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setToDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_device_id = $var;

        return $this;
    }

    /**
     *消息时间，单位ms
     *
     * 
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     *消息时间，单位ms
     *
     * 
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

}

