<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/group.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 
 */
class GroupMemberProfile extends \Google\Protobuf\Internal\Message
{
    /**
     * 
     */
    private $role = 0;
    /**
     * 
     */
    private $profile = null;

    public function __construct() {
        \GPBMetadata\Core\Group::initOnce();
        parent::__construct();
    }

    /**
     * 
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * 
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkEnum($var, \Akaxin\Proto\Core\GroupMemberRole::class);
        $this->role = $var;

        return $this;
    }

    /**
     * 
     * @return \Akaxin\Proto\Core\UserProfile
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * 
     * @param \Akaxin\Proto\Core\UserProfile $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\UserProfile::class);
        $this->profile = $var;

        return $this;
    }

}

