<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *撤回的消息，不用入库
 *
 * Generated from protobuf message <code>core.GroupRecall</code>
 */
class GroupRecall extends \Google\Protobuf\Internal\Message
{
    /**
     *撤回消息的ID
     *
     * Generated from protobuf field <code>string msg_id = 1;</code>
     */
    private $msg_id = '';
    /**
     * Generated from protobuf field <code>string site_user_id = 2;</code>
     */
    private $site_user_id = '';
    /**
     * Generated from protobuf field <code>string site_group_id = 3;</code>
     */
    private $site_group_id = '';
    /**
     *撤回的消息ID
     *
     * Generated from protobuf field <code>string recall_msg_id = 4;</code>
     */
    private $recall_msg_id = '';
    /**
     *消息时间，单位ms,（撤回消息客户端需要判断是否超过2minutes）
     *
     * Generated from protobuf field <code>int64 time = 5;</code>
     */
    private $time = 0;

    public function __construct() {
        \GPBMetadata\Core\Core::initOnce();
        parent::__construct();
    }

    /**
     *撤回消息的ID
     *
     * Generated from protobuf field <code>string msg_id = 1;</code>
     * @return string
     */
    public function getMsgId()
    {
        return $this->msg_id;
    }

    /**
     *撤回消息的ID
     *
     * Generated from protobuf field <code>string msg_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string site_user_id = 2;</code>
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->site_user_id;
    }

    /**
     * Generated from protobuf field <code>string site_user_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string site_group_id = 3;</code>
     * @return string
     */
    public function getSiteGroupId()
    {
        return $this->site_group_id;
    }

    /**
     * Generated from protobuf field <code>string site_group_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_group_id = $var;

        return $this;
    }

    /**
     *撤回的消息ID
     *
     * Generated from protobuf field <code>string recall_msg_id = 4;</code>
     * @return string
     */
    public function getRecallMsgId()
    {
        return $this->recall_msg_id;
    }

    /**
     *撤回的消息ID
     *
     * Generated from protobuf field <code>string recall_msg_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRecallMsgId($var)
    {
        GPBUtil::checkString($var, True);
        $this->recall_msg_id = $var;

        return $this;
    }

    /**
     *消息时间，单位ms,（撤回消息客户端需要判断是否超过2minutes）
     *
     * Generated from protobuf field <code>int64 time = 5;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     *消息时间，单位ms,（撤回消息客户端需要判断是否超过2minutes）
     *
     * Generated from protobuf field <code>int64 time = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

}

