<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/config.proto

namespace Akaxin\Proto\Core;

/**
 *邀请码枚举
 *
 * Protobuf enum <code>Core\InviteCodeConfig</code>
 */
class InviteCodeConfig
{
    /**
     *不需要
     *
     * Generated from protobuf enum <code>UIC_NO = 0;</code>
     */
    const UIC_NO = 0;
    /**
     *关闭邀请码
     *
     * Generated from protobuf enum <code>UIC_YES = 1;</code>
     */
    const UIC_YES = 1;
}

