<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/push.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *支持站点批量发送push的功能
 *
 * 
 */
class Notifications extends \Google\Protobuf\Internal\Message
{
    /**
     *站点服务地址eg->127.0.0.1:2021
     *
     * 
     */
    private $site_server = '';
    /**
     *站点服务名称
     *
     * 
     */
    private $push_title = '';
    /**
     *push的副标题
     *
     * 
     */
    private $push_subtitle = '';
    /**
     *展示的内容
     *
     * 
     */
    private $push_alert = '';
    /**
     *Push跳转位置
     *
     * 
     */
    private $push_goto = '';
    /**
     *气泡展示个数，默认气泡数1
     *
     * 
     */
    private $push_badge = 0;
    /**
     *声音
     *
     * 
     */
    private $push_sound = '';

    public function __construct() {
        \GPBMetadata\Core\Push::initOnce();
        parent::__construct();
    }

    /**
     *站点服务地址eg->127.0.0.1:2021
     *
     * 
     * @return string
     */
    public function getSiteServer()
    {
        return $this->site_server;
    }

    /**
     *站点服务地址eg->127.0.0.1:2021
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteServer($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_server = $var;

        return $this;
    }

    /**
     *站点服务名称
     *
     * 
     * @return string
     */
    public function getPushTitle()
    {
        return $this->push_title;
    }

    /**
     *站点服务名称
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setPushTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->push_title = $var;

        return $this;
    }

    /**
     *push的副标题
     *
     * 
     * @return string
     */
    public function getPushSubtitle()
    {
        return $this->push_subtitle;
    }

    /**
     *push的副标题
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setPushSubtitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->push_subtitle = $var;

        return $this;
    }

    /**
     *展示的内容
     *
     * 
     * @return string
     */
    public function getPushAlert()
    {
        return $this->push_alert;
    }

    /**
     *展示的内容
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setPushAlert($var)
    {
        GPBUtil::checkString($var, True);
        $this->push_alert = $var;

        return $this;
    }

    /**
     *Push跳转位置
     *
     * 
     * @return string
     */
    public function getPushGoto()
    {
        return $this->push_goto;
    }

    /**
     *Push跳转位置
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setPushGoto($var)
    {
        GPBUtil::checkString($var, True);
        $this->push_goto = $var;

        return $this;
    }

    /**
     *气泡展示个数，默认气泡数1
     *
     * 
     * @return int
     */
    public function getPushBadge()
    {
        return $this->push_badge;
    }

    /**
     *气泡展示个数，默认气泡数1
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setPushBadge($var)
    {
        GPBUtil::checkInt32($var);
        $this->push_badge = $var;

        return $this;
    }

    /**
     *声音
     *
     * 
     * @return string
     */
    public function getPushSound()
    {
        return $this->push_sound;
    }

    /**
     *声音
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setPushSound($var)
    {
        GPBUtil::checkString($var, True);
        $this->push_sound = $var;

        return $this;
    }

}

