<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/push.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *最简单的用户信息，用于给别人呈现
 *
 * Generated from protobuf message <code>core.Notification</code>
 */
class Notification extends \Google\Protobuf\Internal\Message
{
    /**
     *站点服务地址eg->127.0.0.1:2021
     *
     * Generated from protobuf field <code>string site_server = 1;</code>
     */
    private $site_server = '';
    /**
     *站点服务名称
     *
     * Generated from protobuf field <code>string push_title = 2;</code>
     */
    private $push_title = '';
    /**
     *展示的内容
     *
     * Generated from protobuf field <code>string push_alert = 3;</code>
     */
    private $push_alert = '';
    /**
     *Push跳转位置
     *
     * Generated from protobuf field <code>string push_goto = 4;</code>
     */
    private $push_goto = '';
    /**
     *气泡展示个数，默认气泡数1
     *
     * Generated from protobuf field <code>int32 push_badge = 5;</code>
     */
    private $push_badge = 0;
    /**
     *声音
     *
     * Generated from protobuf field <code>string push_sound = 6;</code>
     */
    private $push_sound = '';
    /**
     *用户id，这个地方需要使用Global User ID
     *
     * Generated from protobuf field <code>string user_id = 7;</code>
     */
    private $user_id = '';
    /**
     *接受者用户的token
     *
     * Generated from protobuf field <code>string user_token = 8;</code>
     */
    private $user_token = '';
    /**
     *push消息发送者或者群ID，这里使用站点siteUserId或者groupId
     *
     * Generated from protobuf field <code>string push_from_id = 9;</code>
     */
    private $push_from_id = '';
    /**
     *发送着用户名称或者群名称
     *
     * Generated from protobuf field <code>string push_from_name = 10;</code>
     */
    private $push_from_name = '';

    public function __construct() {
        \GPBMetadata\Core\Push::initOnce();
        parent::__construct();
    }

    /**
     *站点服务地址eg->127.0.0.1:2021
     *
     * Generated from protobuf field <code>string site_server = 1;</code>
     * @return string
     */
    public function getSiteServer()
    {
        return $this->site_server;
    }

    /**
     *站点服务地址eg->127.0.0.1:2021
     *
     * Generated from protobuf field <code>string site_server = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteServer($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_server = $var;

        return $this;
    }

    /**
     *站点服务名称
     *
     * Generated from protobuf field <code>string push_title = 2;</code>
     * @return string
     */
    public function getPushTitle()
    {
        return $this->push_title;
    }

    /**
     *站点服务名称
     *
     * Generated from protobuf field <code>string push_title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPushTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->push_title = $var;

        return $this;
    }

    /**
     *展示的内容
     *
     * Generated from protobuf field <code>string push_alert = 3;</code>
     * @return string
     */
    public function getPushAlert()
    {
        return $this->push_alert;
    }

    /**
     *展示的内容
     *
     * Generated from protobuf field <code>string push_alert = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPushAlert($var)
    {
        GPBUtil::checkString($var, True);
        $this->push_alert = $var;

        return $this;
    }

    /**
     *Push跳转位置
     *
     * Generated from protobuf field <code>string push_goto = 4;</code>
     * @return string
     */
    public function getPushGoto()
    {
        return $this->push_goto;
    }

    /**
     *Push跳转位置
     *
     * Generated from protobuf field <code>string push_goto = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPushGoto($var)
    {
        GPBUtil::checkString($var, True);
        $this->push_goto = $var;

        return $this;
    }

    /**
     *气泡展示个数，默认气泡数1
     *
     * Generated from protobuf field <code>int32 push_badge = 5;</code>
     * @return int
     */
    public function getPushBadge()
    {
        return $this->push_badge;
    }

    /**
     *气泡展示个数，默认气泡数1
     *
     * Generated from protobuf field <code>int32 push_badge = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPushBadge($var)
    {
        GPBUtil::checkInt32($var);
        $this->push_badge = $var;

        return $this;
    }

    /**
     *声音
     *
     * Generated from protobuf field <code>string push_sound = 6;</code>
     * @return string
     */
    public function getPushSound()
    {
        return $this->push_sound;
    }

    /**
     *声音
     *
     * Generated from protobuf field <code>string push_sound = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPushSound($var)
    {
        GPBUtil::checkString($var, True);
        $this->push_sound = $var;

        return $this;
    }

    /**
     *用户id，这个地方需要使用Global User ID
     *
     * Generated from protobuf field <code>string user_id = 7;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户id，这个地方需要使用Global User ID
     *
     * Generated from protobuf field <code>string user_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     *接受者用户的token
     *
     * Generated from protobuf field <code>string user_token = 8;</code>
     * @return string
     */
    public function getUserToken()
    {
        return $this->user_token;
    }

    /**
     *接受者用户的token
     *
     * Generated from protobuf field <code>string user_token = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUserToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_token = $var;

        return $this;
    }

    /**
     *push消息发送者或者群ID，这里使用站点siteUserId或者groupId
     *
     * Generated from protobuf field <code>string push_from_id = 9;</code>
     * @return string
     */
    public function getPushFromId()
    {
        return $this->push_from_id;
    }

    /**
     *push消息发送者或者群ID，这里使用站点siteUserId或者groupId
     *
     * Generated from protobuf field <code>string push_from_id = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setPushFromId($var)
    {
        GPBUtil::checkString($var, True);
        $this->push_from_id = $var;

        return $this;
    }

    /**
     *发送着用户名称或者群名称
     *
     * Generated from protobuf field <code>string push_from_name = 10;</code>
     * @return string
     */
    public function getPushFromName()
    {
        return $this->push_from_name;
    }

    /**
     *发送着用户名称或者群名称
     *
     * Generated from protobuf field <code>string push_from_name = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setPushFromName($var)
    {
        GPBUtil::checkString($var, True);
        $this->push_from_name = $var;

        return $this;
    }

}

