<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/plugin.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * site 与plugin之间交互传输的package包
 *
 * 
 */
class ProxyPluginPackage extends \Google\Protobuf\Internal\Message
{
    /**
     *header
     *
     * 
     */
    private $plugin_header;
    /**
     *data在赋值之前先base64
     *site -> plugin 是开发者自定义的格式
     *plugin -> site 为具体请求的proto格式
     *
     * 
     */
    private $data = '';
    /**
     *error信息
     *
     * 
     */
    private $error_info = null;

    public function __construct() {
        \GPBMetadata\Core\Plugin::initOnce();
        parent::__construct();
    }

    /**
     *header
     *
     * 
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPluginHeader()
    {
        return $this->plugin_header;
    }

    /**
     *header
     *
     * 
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setPluginHeader($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::STRING);
        $this->plugin_header = $arr;

        return $this;
    }

    /**
     *data在赋值之前先base64
     *site -> plugin 是开发者自定义的格式
     *plugin -> site 为具体请求的proto格式
     *
     * 
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     *data在赋值之前先base64
     *site -> plugin 是开发者自定义的格式
     *plugin -> site 为具体请求的proto格式
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->data = $var;

        return $this;
    }

    /**
     *error信息
     *
     * 
     * @return \Akaxin\Proto\Core\ErrorInfo
     */
    public function getErrorInfo()
    {
        return $this->error_info;
    }

    /**
     *error信息
     *
     * 
     * @param \Akaxin\Proto\Core\ErrorInfo $var
     * @return $this
     */
    public function setErrorInfo($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\ErrorInfo::class);
        $this->error_info = $var;

        return $this;
    }

}

