<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/push.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 
 */
class PushToUser extends \Google\Protobuf\Internal\Message
{
    /**
     *接受者：globalUserID,
     *
     * 
     */
    private $global_user_id = '';
    /**
     *接受者：用户的token
     *
     * 
     */
    private $user_token = '';

    public function __construct() {
        \GPBMetadata\Core\Push::initOnce();
        parent::__construct();
    }

    /**
     *接受者：globalUserID,
     *
     * 
     * @return string
     */
    public function getGlobalUserId()
    {
        return $this->global_user_id;
    }

    /**
     *接受者：globalUserID,
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setGlobalUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->global_user_id = $var;

        return $this;
    }

    /**
     *接受者：用户的token
     *
     * 
     * @return string
     */
    public function getUserToken()
    {
        return $this->user_token;
    }

    /**
     *接受者：用户的token
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setUserToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_token = $var;

        return $this;
    }

}

