<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/push.proto

namespace Akaxin\Proto\Core;

/**
 * Protobuf enum <code>Core\PushType</code>
 */
class PushType
{
    /**
     *系统通知
     *
     * Generated from protobuf enum <code>PUSH_NOTICE = 0;</code>
     */
    const PUSH_NOTICE = 0;
    /**
     * Generated from protobuf enum <code>PUSH_MSG_STATUS = 1;</code>
     */
    const PUSH_MSG_STATUS = 1;
    /**
     *这个不是废弃了么？
     *
     * Generated from protobuf enum <code>PUSH_MSG_FINISH = 2;</code>
     */
    const PUSH_MSG_FINISH = 2;
    /**
     * Generated from protobuf enum <code>PUSH_TEXT = 3;</code>
     */
    const PUSH_TEXT = 3;
    /**
     * Generated from protobuf enum <code>PUSH_SECRET_TEXT = 4;</code>
     */
    const PUSH_SECRET_TEXT = 4;
    /**
     * Generated from protobuf enum <code>PUSH_GROUP_TEXT = 5;</code>
     */
    const PUSH_GROUP_TEXT = 5;
    /**
     * Generated from protobuf enum <code>PUSH_GROUP_SECRET_TEXT = 6;</code>
     */
    const PUSH_GROUP_SECRET_TEXT = 6;
    /**
     * Generated from protobuf enum <code>PUSH_IMAGE = 7;</code>
     */
    const PUSH_IMAGE = 7;
    /**
     * Generated from protobuf enum <code>PUSH_SECRET_IMAGE = 8;</code>
     */
    const PUSH_SECRET_IMAGE = 8;
    /**
     * Generated from protobuf enum <code>PUSH_GROUP_IMAGE = 9;</code>
     */
    const PUSH_GROUP_IMAGE = 9;
    /**
     * Generated from protobuf enum <code>PUSH_GROUP_SECRET_IMAGE = 10;</code>
     */
    const PUSH_GROUP_SECRET_IMAGE = 10;
    /**
     * Generated from protobuf enum <code>PUSH_VOICE = 11;</code>
     */
    const PUSH_VOICE = 11;
    /**
     * Generated from protobuf enum <code>PUSH_SECRET_VOICE = 12;</code>
     */
    const PUSH_SECRET_VOICE = 12;
    /**
     * Generated from protobuf enum <code>PUSH_GROUP_VOICE = 13;</code>
     */
    const PUSH_GROUP_VOICE = 13;
    /**
     * Generated from protobuf enum <code>PUSH_GROUP_SECRET_VOICE = 14;</code>
     */
    const PUSH_GROUP_SECRET_VOICE = 14;
    /**
     * Generated from protobuf enum <code>PUSH_MAP = 15;</code>
     */
    const PUSH_MAP = 15;
    /**
     * Generated from protobuf enum <code>PUSH_SECRET_MAP = 16;</code>
     */
    const PUSH_SECRET_MAP = 16;
    /**
     * Generated from protobuf enum <code>PUSH_GROUP_MAP = 17;</code>
     */
    const PUSH_GROUP_MAP = 17;
    /**
     * Generated from protobuf enum <code>PUSH_GROUP_SECRET_MAP = 18;</code>
     */
    const PUSH_GROUP_SECRET_MAP = 18;
    /**
     *二人消息中的通知消息
     *
     * Generated from protobuf enum <code>PUSH_U2_NOTICE = 19;</code>
     */
    const PUSH_U2_NOTICE = 19;
    /**
     *群消息中的通知消息
     *
     * Generated from protobuf enum <code>PUSH_GROUP_NOTICE = 20;</code>
     */
    const PUSH_GROUP_NOTICE = 20;
    /**
     *申请添加好友通知
     *
     * Generated from protobuf enum <code>PUSH_APPLY_FRIEND_NOTICE = 100;</code>
     */
    const PUSH_APPLY_FRIEND_NOTICE = 100;
}

