<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/config.proto

namespace Akaxin\Proto\Core;

/**
 *实名枚举
 *
 * Protobuf enum <code>Core\RealNameConfig</code>
 */
class RealNameConfig
{
    /**
     *匿名方式
     *
     * Generated from protobuf enum <code>REALNAME_NO = 0;</code>
     */
    const REALNAME_NO = 0;
    /**
     *实名方式,必须用户是实名
     *
     * Generated from protobuf enum <code>REALNAME_YES = 1;</code>
     */
    const REALNAME_YES = 1;
    /**
     *优先实名方式，其次接受非实名用户
     *
     * Generated from protobuf enum <code>REALNAME_YES_NO = 2;</code>
     */
    const REALNAME_YES_NO = 2;
}

