<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/device.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *设备简要信息
 *
 * Generated from protobuf message <code>core.SimpleDeviceProfile</code>
 */
class SimpleDeviceProfile extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string device_id = 1;</code>
     */
    private $device_id = '';
    /**
     * Generated from protobuf field <code>string device_name = 2;</code>
     */
    private $device_name = '';
    /**
     * Generated from protobuf field <code>string user_device_pubk = 3;</code>
     */
    private $user_device_pubk = '';
    /**
     * Generated from protobuf field <code>int64 last_login_time = 4;</code>
     */
    private $last_login_time = 0;

    public function __construct() {
        \GPBMetadata\Core\Device::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string device_id = 1;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>string device_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string device_name = 2;</code>
     * @return string
     */
    public function getDeviceName()
    {
        return $this->device_name;
    }

    /**
     * Generated from protobuf field <code>string device_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_device_pubk = 3;</code>
     * @return string
     */
    public function getUserDevicePubk()
    {
        return $this->user_device_pubk;
    }

    /**
     * Generated from protobuf field <code>string user_device_pubk = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDevicePubk($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_device_pubk = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 last_login_time = 4;</code>
     * @return int|string
     */
    public function getLastLoginTime()
    {
        return $this->last_login_time;
    }

    /**
     * Generated from protobuf field <code>int64 last_login_time = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastLoginTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_login_time = $var;

        return $this;
    }

}

