<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/group.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 
 */
class SimpleGroupProfile extends \Google\Protobuf\Internal\Message
{
    /**
     * 
     */
    private $group_id = '';
    /**
     * 
     */
    private $group_name = '';
    /**
     * 
     */
    private $group_icon = '';

    public function __construct() {
        \GPBMetadata\Core\Group::initOnce();
        parent::__construct();
    }

    /**
     * 
     * @return string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * 
     * @param string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_id = $var;

        return $this;
    }

    /**
     * 
     * @return string
     */
    public function getGroupName()
    {
        return $this->group_name;
    }

    /**
     * 
     * @param string $var
     * @return $this
     */
    public function setGroupName($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_name = $var;

        return $this;
    }

    /**
     * 
     * @return string
     */
    public function getGroupIcon()
    {
        return $this->group_icon;
    }

    /**
     * 
     * @param string $var
     * @return $this
     */
    public function setGroupIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_icon = $var;

        return $this;
    }

}

