<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/user.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>core.SimpleUserProfile</code>
 */
class SimpleUserProfile extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string site_user_id = 1;</code>
     */
    private $site_user_id = '';
    /**
     *如果用户有备注，这里使用备注，如果没有使用昵称
     *
     * Generated from protobuf field <code>string user_name = 2;</code>
     */
    private $user_name = '';
    /**
     * Generated from protobuf field <code>string user_photo = 3;</code>
     */
    private $user_photo = '';
    /**
     * Generated from protobuf field <code>.core.UserStatus user_status = 4;</code>
     */
    private $user_status = 0;
    /**
     *用户唯一登陆名，站点唯一
     *
     * Generated from protobuf field <code>string site_login_name = 5;</code>
     */
    private $site_login_name = '';
    /**
     *用户个人设置的昵称
     *
     * Generated from protobuf field <code>string nick_name = 6;</code>
     */
    private $nick_name = '';
    /**
     *张三->  zhangsan
     *
     * Generated from protobuf field <code>string username_in_latin = 7;</code>
     */
    private $username_in_latin = '';

    public function __construct() {
        \GPBMetadata\Core\User::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string site_user_id = 1;</code>
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->site_user_id;
    }

    /**
     * Generated from protobuf field <code>string site_user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_user_id = $var;

        return $this;
    }

    /**
     *如果用户有备注，这里使用备注，如果没有使用昵称
     *
     * Generated from protobuf field <code>string user_name = 2;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->user_name;
    }

    /**
     *如果用户有备注，这里使用备注，如果没有使用昵称
     *
     * Generated from protobuf field <code>string user_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_photo = 3;</code>
     * @return string
     */
    public function getUserPhoto()
    {
        return $this->user_photo;
    }

    /**
     * Generated from protobuf field <code>string user_photo = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserPhoto($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_photo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.core.UserStatus user_status = 4;</code>
     * @return int
     */
    public function getUserStatus()
    {
        return $this->user_status;
    }

    /**
     * Generated from protobuf field <code>.core.UserStatus user_status = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setUserStatus($var)
    {
        GPBUtil::checkEnum($var, \Akaxin\Proto\Core\UserStatus::class);
        $this->user_status = $var;

        return $this;
    }

    /**
     *用户唯一登陆名，站点唯一
     *
     * Generated from protobuf field <code>string site_login_name = 5;</code>
     * @return string
     */
    public function getSiteLoginName()
    {
        return $this->site_login_name;
    }

    /**
     *用户唯一登陆名，站点唯一
     *
     * Generated from protobuf field <code>string site_login_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteLoginName($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_login_name = $var;

        return $this;
    }

    /**
     *用户个人设置的昵称
     *
     * Generated from protobuf field <code>string nick_name = 6;</code>
     * @return string
     */
    public function getNickName()
    {
        return $this->nick_name;
    }

    /**
     *用户个人设置的昵称
     *
     * Generated from protobuf field <code>string nick_name = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setNickName($var)
    {
        GPBUtil::checkString($var, True);
        $this->nick_name = $var;

        return $this;
    }

    /**
     *张三->  zhangsan
     *
     * Generated from protobuf field <code>string username_in_latin = 7;</code>
     * @return string
     */
    public function getUsernameInLatin()
    {
        return $this->username_in_latin;
    }

    /**
     *张三->  zhangsan
     *
     * Generated from protobuf field <code>string username_in_latin = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUsernameInLatin($var)
    {
        GPBUtil::checkString($var, True);
        $this->username_in_latin = $var;

        return $this;
    }

}

