<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/config.proto

namespace Akaxin\Proto\Core;

/**
 *站点开启，关闭状态
 *
 * Protobuf enum <code>Core\SiteStatusConfig</code>
 */
class SiteStatusConfig
{
    /**
     *站点关闭状态
     *
     * Generated from protobuf enum <code>CLOSE = 0;</code>
     */
    const CLOSE = 0;
    /**
     *站点开启状态
     *
     * Generated from protobuf enum <code>OPEN = 1;</code>
     */
    const OPEN = 1;
}

