<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/config.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *站点后台管理配置
 *
 * 
 */
class SiteBackConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * 
     */
    private $site_config;

    public function __construct() {
        \GPBMetadata\Core\Config::initOnce();
        parent::__construct();
    }

    /**
     * 
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSiteConfig()
    {
        return $this->site_config;
    }

    /**
     * 
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSiteConfig($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::STRING);
        $this->site_config = $arr;

        return $this;
    }

}

