<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/config.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 站点配置信息
 *
 * 
 */
class SiteConfig extends \Google\Protobuf\Internal\Message
{
    /**
     *站点ip
     *
     * 
     */
    private $site_address = '';
    /**
     *站点地址
     *
     * 
     */
    private $site_port = 0;
    /**
     *站点名称
     *
     * 
     */
    private $site_name = '';
    /**
     *站点logo
     *
     * 
     */
    private $site_logo = '';
    /**
     *站点版本
     *
     * 
     */
    private $site_version = '';
    /**
     *站点介绍
     *
     * 
     */
    private $site_introduction = '';
    /**
     *站点是否需要实名
     *
     * 
     */
    private $real_name_config = 0;
    /**
     *支持图片大小（width x length）
     *
     * 
     */
    private $pic_size = '';
    /**
     *站点状态
     *
     * 
     */
    private $site_status_config = 0;
    /**
     *站点状态说明，一般关闭站点情况使用
     *
     * 
     */
    private $site_status_info = '';
    /**
     *二人消息加密状态
     *
     * 
     */
    private $u2_encryption_config = 0;
    /**
     *站点注册是否需要邀请码
     *
     * 
     */
    private $invite_code_config = 0;

    public function __construct() {
        \GPBMetadata\Core\Config::initOnce();
        parent::__construct();
    }

    /**
     *站点ip
     *
     * 
     * @return string
     */
    public function getSiteAddress()
    {
        return $this->site_address;
    }

    /**
     *站点ip
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_address = $var;

        return $this;
    }

    /**
     *站点地址
     *
     * 
     * @return int
     */
    public function getSitePort()
    {
        return $this->site_port;
    }

    /**
     *站点地址
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setSitePort($var)
    {
        GPBUtil::checkInt32($var);
        $this->site_port = $var;

        return $this;
    }

    /**
     *站点名称
     *
     * 
     * @return string
     */
    public function getSiteName()
    {
        return $this->site_name;
    }

    /**
     *站点名称
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteName($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_name = $var;

        return $this;
    }

    /**
     *站点logo
     *
     * 
     * @return string
     */
    public function getSiteLogo()
    {
        return $this->site_logo;
    }

    /**
     *站点logo
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteLogo($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_logo = $var;

        return $this;
    }

    /**
     *站点版本
     *
     * 
     * @return string
     */
    public function getSiteVersion()
    {
        return $this->site_version;
    }

    /**
     *站点版本
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_version = $var;

        return $this;
    }

    /**
     *站点介绍
     *
     * 
     * @return string
     */
    public function getSiteIntroduction()
    {
        return $this->site_introduction;
    }

    /**
     *站点介绍
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteIntroduction($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_introduction = $var;

        return $this;
    }

    /**
     *站点是否需要实名
     *
     * 
     * @return int
     */
    public function getRealNameConfig()
    {
        return $this->real_name_config;
    }

    /**
     *站点是否需要实名
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setRealNameConfig($var)
    {
        GPBUtil::checkEnum($var, \Akaxin\Proto\Core\RealNameConfig::class);
        $this->real_name_config = $var;

        return $this;
    }

    /**
     *支持图片大小（width x length）
     *
     * 
     * @return string
     */
    public function getPicSize()
    {
        return $this->pic_size;
    }

    /**
     *支持图片大小（width x length）
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setPicSize($var)
    {
        GPBUtil::checkString($var, True);
        $this->pic_size = $var;

        return $this;
    }

    /**
     *站点状态
     *
     * 
     * @return int
     */
    public function getSiteStatusConfig()
    {
        return $this->site_status_config;
    }

    /**
     *站点状态
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setSiteStatusConfig($var)
    {
        GPBUtil::checkEnum($var, \Akaxin\Proto\Core\SiteStatusConfig::class);
        $this->site_status_config = $var;

        return $this;
    }

    /**
     *站点状态说明，一般关闭站点情况使用
     *
     * 
     * @return string
     */
    public function getSiteStatusInfo()
    {
        return $this->site_status_info;
    }

    /**
     *站点状态说明，一般关闭站点情况使用
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteStatusInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_status_info = $var;

        return $this;
    }

    /**
     *二人消息加密状态
     *
     * 
     * @return int
     */
    public function getU2EncryptionConfig()
    {
        return $this->u2_encryption_config;
    }

    /**
     *二人消息加密状态
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setU2EncryptionConfig($var)
    {
        GPBUtil::checkEnum($var, \Akaxin\Proto\Core\U2EncryptionConfig::class);
        $this->u2_encryption_config = $var;

        return $this;
    }

    /**
     *站点注册是否需要邀请码
     *
     * 
     * @return int
     */
    public function getInviteCodeConfig()
    {
        return $this->invite_code_config;
    }

    /**
     *站点注册是否需要邀请码
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setInviteCodeConfig($var)
    {
        GPBUtil::checkEnum($var, \Akaxin\Proto\Core\InviteCodeConfig::class);
        $this->invite_code_config = $var;

        return $this;
    }

}

