<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/config.proto

namespace Akaxin\Proto\Core;

/**
 *二人加密状态枚举
 *
 * Protobuf enum <code>Core\U2EncryptionConfig</code>
 */
class U2EncryptionConfig
{
    /**
     *二人加密关闭
     *
     * Generated from protobuf enum <code>U2_CLOSE = 0;</code>
     */
    const U2_CLOSE = 0;
    /**
     *二人加密开启
     *
     * Generated from protobuf enum <code>U2_OPEN = 1;</code>
     */
    const U2_OPEN = 1;
}

