<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *加密地理位置消息
 *
 * Generated from protobuf message <code>core.U2SecretMap</code>
 */
class U2SecretMap extends \Google\Protobuf\Internal\Message
{
    /**
     *消息id
     *
     * Generated from protobuf field <code>string msg_id = 1;</code>
     */
    private $msg_id = '';
    /**
     *from
     *
     * Generated from protobuf field <code>string site_user_id = 2;</code>
     */
    private $site_user_id = '';
    /**
     *to
     *
     * Generated from protobuf field <code>string site_friend_id = 3;</code>
     */
    private $site_friend_id = '';
    /**
     *加密Base64经度
     *
     * Generated from protobuf field <code>string base64_lng = 4;</code>
     */
    private $base64_lng = '';
    /**
     *加密Base64纬度
     *
     * Generated from protobuf field <code>string base64_lat = 5;</code>
     */
    private $base64_lat = '';
    /**
     *Base64的加密key，用于AES加密使用
     *
     * Generated from protobuf field <code>string base64_ts_key = 6;</code>
     */
    private $base64_ts_key = '';
    /**
     *接受者的设备ID
     *
     * Generated from protobuf field <code>string to_device_id = 7;</code>
     */
    private $to_device_id = '';
    /**
     *消息时间，单位ms
     *
     * Generated from protobuf field <code>int64 time = 8;</code>
     */
    private $time = 0;

    public function __construct() {
        \GPBMetadata\Core\Core::initOnce();
        parent::__construct();
    }

    /**
     *消息id
     *
     * Generated from protobuf field <code>string msg_id = 1;</code>
     * @return string
     */
    public function getMsgId()
    {
        return $this->msg_id;
    }

    /**
     *消息id
     *
     * Generated from protobuf field <code>string msg_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg_id = $var;

        return $this;
    }

    /**
     *from
     *
     * Generated from protobuf field <code>string site_user_id = 2;</code>
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->site_user_id;
    }

    /**
     *from
     *
     * Generated from protobuf field <code>string site_user_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_user_id = $var;

        return $this;
    }

    /**
     *to
     *
     * Generated from protobuf field <code>string site_friend_id = 3;</code>
     * @return string
     */
    public function getSiteFriendId()
    {
        return $this->site_friend_id;
    }

    /**
     *to
     *
     * Generated from protobuf field <code>string site_friend_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteFriendId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_friend_id = $var;

        return $this;
    }

    /**
     *加密Base64经度
     *
     * Generated from protobuf field <code>string base64_lng = 4;</code>
     * @return string
     */
    public function getBase64Lng()
    {
        return $this->base64_lng;
    }

    /**
     *加密Base64经度
     *
     * Generated from protobuf field <code>string base64_lng = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBase64Lng($var)
    {
        GPBUtil::checkString($var, True);
        $this->base64_lng = $var;

        return $this;
    }

    /**
     *加密Base64纬度
     *
     * Generated from protobuf field <code>string base64_lat = 5;</code>
     * @return string
     */
    public function getBase64Lat()
    {
        return $this->base64_lat;
    }

    /**
     *加密Base64纬度
     *
     * Generated from protobuf field <code>string base64_lat = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBase64Lat($var)
    {
        GPBUtil::checkString($var, True);
        $this->base64_lat = $var;

        return $this;
    }

    /**
     *Base64的加密key，用于AES加密使用
     *
     * Generated from protobuf field <code>string base64_ts_key = 6;</code>
     * @return string
     */
    public function getBase64TsKey()
    {
        return $this->base64_ts_key;
    }

    /**
     *Base64的加密key，用于AES加密使用
     *
     * Generated from protobuf field <code>string base64_ts_key = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBase64TsKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->base64_ts_key = $var;

        return $this;
    }

    /**
     *接受者的设备ID
     *
     * Generated from protobuf field <code>string to_device_id = 7;</code>
     * @return string
     */
    public function getToDeviceId()
    {
        return $this->to_device_id;
    }

    /**
     *接受者的设备ID
     *
     * Generated from protobuf field <code>string to_device_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setToDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_device_id = $var;

        return $this;
    }

    /**
     *消息时间，单位ms
     *
     * Generated from protobuf field <code>int64 time = 8;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     *消息时间，单位ms
     *
     * Generated from protobuf field <code>int64 time = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

}

