<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *二人：内嵌web类型消息
 *
 * Generated from protobuf message <code>core.U2Web</code>
 */
class U2Web extends \Google\Protobuf\Internal\Message
{
    /**
     *消息ID
     *
     * Generated from protobuf field <code>string msg_id = 1;</code>
     */
    private $msg_id = '';
    /**
     *from
     *
     * Generated from protobuf field <code>string site_user_id = 2;</code>
     */
    private $site_user_id = '';
    /**
     *to
     *
     * Generated from protobuf field <code>string site_friend_id = 3;</code>
     */
    private $site_friend_id = '';
    /**
     *统一使用web消息需要的代码内容
     *
     * Generated from protobuf field <code>string web_code = 4;</code>
     */
    private $web_code = '';
    /**
     *web消息的宽度
     *
     * Generated from protobuf field <code>int32 width = 5;</code>
     */
    private $width = 0;
    /**
     *web消息的高度
     *
     * Generated from protobuf field <code>int32 height = 6;</code>
     */
    private $height = 0;
    /**
     *消息时间
     *
     * Generated from protobuf field <code>int64 time = 7;</code>
     */
    private $time = 0;

    public function __construct() {
        \GPBMetadata\Core\Core::initOnce();
        parent::__construct();
    }

    /**
     *消息ID
     *
     * Generated from protobuf field <code>string msg_id = 1;</code>
     * @return string
     */
    public function getMsgId()
    {
        return $this->msg_id;
    }

    /**
     *消息ID
     *
     * Generated from protobuf field <code>string msg_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg_id = $var;

        return $this;
    }

    /**
     *from
     *
     * Generated from protobuf field <code>string site_user_id = 2;</code>
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->site_user_id;
    }

    /**
     *from
     *
     * Generated from protobuf field <code>string site_user_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_user_id = $var;

        return $this;
    }

    /**
     *to
     *
     * Generated from protobuf field <code>string site_friend_id = 3;</code>
     * @return string
     */
    public function getSiteFriendId()
    {
        return $this->site_friend_id;
    }

    /**
     *to
     *
     * Generated from protobuf field <code>string site_friend_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteFriendId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_friend_id = $var;

        return $this;
    }

    /**
     *统一使用web消息需要的代码内容
     *
     * Generated from protobuf field <code>string web_code = 4;</code>
     * @return string
     */
    public function getWebCode()
    {
        return $this->web_code;
    }

    /**
     *统一使用web消息需要的代码内容
     *
     * Generated from protobuf field <code>string web_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setWebCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->web_code = $var;

        return $this;
    }

    /**
     *web消息的宽度
     *
     * Generated from protobuf field <code>int32 width = 5;</code>
     * @return int
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     *web消息的宽度
     *
     * Generated from protobuf field <code>int32 width = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkInt32($var);
        $this->width = $var;

        return $this;
    }

    /**
     *web消息的高度
     *
     * Generated from protobuf field <code>int32 height = 6;</code>
     * @return int
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     *web消息的高度
     *
     * Generated from protobuf field <code>int32 height = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->height = $var;

        return $this;
    }

    /**
     *消息时间
     *
     * Generated from protobuf field <code>int64 time = 7;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     *消息时间
     *
     * Generated from protobuf field <code>int64 time = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

}

