<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/uic.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *最简单的用户信息，用于给别人呈现
 *
 * 
 */
class UicInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *uic_id
     *
     * 
     */
    private $id = 0;
    /**
     *uic
     *
     * 
     */
    private $uic = '';
    /**
     *用户id
     *
     * 
     */
    private $site_user_id = '';
    /**
     *用户名称
     *
     * 
     */
    private $user_name = '';
    /**
     *是否可用的状态
     *
     * 
     */
    private $status = 0;
    /**
     *生成的时间
     *
     * 
     */
    private $create_time = 0;
    /**
     *使用的时间
     *
     * 
     */
    private $use_time = 0;

    public function __construct() {
        \GPBMetadata\Core\Uic::initOnce();
        parent::__construct();
    }

    /**
     *uic_id
     *
     * 
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     *uic_id
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     *uic
     *
     * 
     * @return string
     */
    public function getUic()
    {
        return $this->uic;
    }

    /**
     *uic
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setUic($var)
    {
        GPBUtil::checkString($var, True);
        $this->uic = $var;

        return $this;
    }

    /**
     *用户id
     *
     * 
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->site_user_id;
    }

    /**
     *用户id
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_user_id = $var;

        return $this;
    }

    /**
     *用户名称
     *
     * 
     * @return string
     */
    public function getUserName()
    {
        return $this->user_name;
    }

    /**
     *用户名称
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_name = $var;

        return $this;
    }

    /**
     *是否可用的状态
     *
     * 
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     *是否可用的状态
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Akaxin\Proto\Core\UicStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     *生成的时间
     *
     * 
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     *生成的时间
     *
     * 
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->create_time = $var;

        return $this;
    }

    /**
     *使用的时间
     *
     * 
     * @return int|string
     */
    public function getUseTime()
    {
        return $this->use_time;
    }

    /**
     *使用的时间
     *
     * 
     * @param int|string $var
     * @return $this
     */
    public function setUseTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->use_time = $var;

        return $this;
    }

}

