<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/user.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 
 */
class UserRelationProfile extends \Google\Protobuf\Internal\Message
{
    /**
     *用户的个人资料
     *
     * 
     */
    private $profile = null;
    /**
     *用户A与B的关系
     *
     * 
     */
    private $relation = 0;

    public function __construct() {
        \GPBMetadata\Core\User::initOnce();
        parent::__construct();
    }

    /**
     *用户的个人资料
     *
     * 
     * @return \Akaxin\Proto\Core\SimpleUserProfile
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     *用户的个人资料
     *
     * 
     * @param \Akaxin\Proto\Core\SimpleUserProfile $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\SimpleUserProfile::class);
        $this->profile = $var;

        return $this;
    }

    /**
     *用户A与B的关系
     *
     * 
     * @return int
     */
    public function getRelation()
    {
        return $this->relation;
    }

    /**
     *用户A与B的关系
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setRelation($var)
    {
        GPBUtil::checkEnum($var, \Akaxin\Proto\Core\UserRelation::class);
        $this->relation = $var;

        return $this;
    }

}

