<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/user.proto

namespace Akaxin\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *最简单的用户信息，用于给别人呈现
 *
 * 
 */
class UserProfile extends \Google\Protobuf\Internal\Message
{
    /**
     * 
     */
    private $site_user_id = '';
    /**
     *如果用户有备注，这里使用备注，如果没有使用昵称，修改个人profile昵称，直接把昵称复制这里
     *
     * 
     */
    private $user_name = '';
    /**
     * 
     */
    private $user_photo = '';
    /**
     * 
     */
    private $self_introduce = '';
    /**
     * 
     */
    private $user_status = 0;
    /**
     * 
     */
    private $register_time = 0;
    /**
     *用户唯一登陆名，站点唯一（例如使用：“卡号”表示）
     *
     * 
     */
    private $site_login_id = '';
    /**
     *用户个人设置的昵称
     *
     * 
     */
    private $nick_name = '';
    /**
     *汉字转换拼音
     *
     * 
     */
    private $username_in_latin = '';

    public function __construct() {
        \GPBMetadata\Core\User::initOnce();
        parent::__construct();
    }

    /**
     * 
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->site_user_id;
    }

    /**
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_user_id = $var;

        return $this;
    }

    /**
     *如果用户有备注，这里使用备注，如果没有使用昵称，修改个人profile昵称，直接把昵称复制这里
     *
     * 
     * @return string
     */
    public function getUserName()
    {
        return $this->user_name;
    }

    /**
     *如果用户有备注，这里使用备注，如果没有使用昵称，修改个人profile昵称，直接把昵称复制这里
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_name = $var;

        return $this;
    }

    /**
     * 
     * @return string
     */
    public function getUserPhoto()
    {
        return $this->user_photo;
    }

    /**
     * 
     * @param string $var
     * @return $this
     */
    public function setUserPhoto($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_photo = $var;

        return $this;
    }

    /**
     * 
     * @return string
     */
    public function getSelfIntroduce()
    {
        return $this->self_introduce;
    }

    /**
     * 
     * @param string $var
     * @return $this
     */
    public function setSelfIntroduce($var)
    {
        GPBUtil::checkString($var, True);
        $this->self_introduce = $var;

        return $this;
    }

    /**
     * 
     * @return int
     */
    public function getUserStatus()
    {
        return $this->user_status;
    }

    /**
     * 
     * @param int $var
     * @return $this
     */
    public function setUserStatus($var)
    {
        GPBUtil::checkEnum($var, \Akaxin\Proto\Core\UserStatus::class);
        $this->user_status = $var;

        return $this;
    }

    /**
     * 
     * @return int|string
     */
    public function getRegisterTime()
    {
        return $this->register_time;
    }

    /**
     * 
     * @param int|string $var
     * @return $this
     */
    public function setRegisterTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->register_time = $var;

        return $this;
    }

    /**
     *用户唯一登陆名，站点唯一（例如使用：“卡号”表示）
     *
     * 
     * @return string
     */
    public function getSiteLoginId()
    {
        return $this->site_login_id;
    }

    /**
     *用户唯一登陆名，站点唯一（例如使用：“卡号”表示）
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteLoginId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_login_id = $var;

        return $this;
    }

    /**
     *用户个人设置的昵称
     *
     * 
     * @return string
     */
    public function getNickName()
    {
        return $this->nick_name;
    }

    /**
     *用户个人设置的昵称
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setNickName($var)
    {
        GPBUtil::checkString($var, True);
        $this->nick_name = $var;

        return $this;
    }

    /**
     *汉字转换拼音
     *
     * 
     * @return string
     */
    public function getUsernameInLatin()
    {
        return $this->username_in_latin;
    }

    /**
     *汉字转换拼音
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setUsernameInLatin($var)
    {
        GPBUtil::checkString($var, True);
        $this->username_in_latin = $var;

        return $this;
    }

}

