<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_friend_add.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.HaiFriendAddRequest</code>
 */
class HaiFriendAddRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *添加好友的用户
     *
     * Generated from protobuf field <code>string site_friend_id = 1;</code>
     */
    private $site_friend_id = '';

    public function __construct() {
        \GPBMetadata\Plugin\HaiFriendAdd::initOnce();
        parent::__construct();
    }

    /**
     *添加好友的用户
     *
     * Generated from protobuf field <code>string site_friend_id = 1;</code>
     * @return string
     */
    public function getSiteFriendId()
    {
        return $this->site_friend_id;
    }

    /**
     *添加好友的用户
     *
     * Generated from protobuf field <code>string site_friend_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteFriendId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_friend_id = $var;

        return $this;
    }

}

