<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_friend_apply.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *A->B 发送好友请求
 *----
 *接口名
 *----
 * /hai/friend/apply
 *错误码
 *----
 *- success
 *- error.alert
 *
 * 
 */
class HaiFriendApplyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 发起好友请求的用户
     *
     * 
     */
    private $site_user_id = '';
    /**
     * 目标用户
     *
     * 
     */
    private $friend_site_user_id = '';
    /**
     * 申请理由
     *
     * 
     */
    private $apply_reason = '';

    public function __construct() {
        \GPBMetadata\Plugin\HaiFriendApply::initOnce();
        parent::__construct();
    }

    /**
     * 发起好友请求的用户
     *
     * 
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->site_user_id;
    }

    /**
     * 发起好友请求的用户
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_user_id = $var;

        return $this;
    }

    /**
     * 目标用户
     *
     * 
     * @return string
     */
    public function getFriendSiteUserId()
    {
        return $this->friend_site_user_id;
    }

    /**
     * 目标用户
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setFriendSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->friend_site_user_id = $var;

        return $this;
    }

    /**
     * 申请理由
     *
     * 
     * @return string
     */
    public function getApplyReason()
    {
        return $this->apply_reason;
    }

    /**
     * 申请理由
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setApplyReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->apply_reason = $var;

        return $this;
    }

}

