<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_friend_relations.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.HaiFriendRelationsRequest</code>
 */
class HaiFriendRelationsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *需要查询关系的用户ID
     *
     * Generated from protobuf field <code>repeated string user_id = 1;</code>
     */
    private $user_id;

    public function __construct() {
        \GPBMetadata\Plugin\HaiFriendRelations::initOnce();
        parent::__construct();
    }

    /**
     *需要查询关系的用户ID
     *
     * Generated from protobuf field <code>repeated string user_id = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *需要查询关系的用户ID
     *
     * Generated from protobuf field <code>repeated string user_id = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->user_id = $arr;

        return $this;
    }

}

