<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_friend_phone.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.HaiFriendPhoneRequest</code>
 */
class HaiFriendPhoneRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *用户的站点ID
     *
     * Generated from protobuf field <code>string site_user_id = 1;</code>
     */
    private $site_user_id = '';

    public function __construct() {
        \GPBMetadata\Plugin\HaiFriendPhone::initOnce();
        parent::__construct();
    }

    /**
     *用户的站点ID
     *
     * Generated from protobuf field <code>string site_user_id = 1;</code>
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->site_user_id;
    }

    /**
     *用户的站点ID
     *
     * Generated from protobuf field <code>string site_user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_user_id = $var;

        return $this;
    }

}

