<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_friend_relations.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 
 */
class HaiFriendRelationsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *查询的结果
     *
     * 
     */
    private $user_profile;

    public function __construct() {
        \GPBMetadata\Plugin\HaiFriendRelations::initOnce();
        parent::__construct();
    }

    /**
     *查询的结果
     *
     * 
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserProfile()
    {
        return $this->user_profile;
    }

    /**
     *查询的结果
     *
     * 
     * @param \Akaxin\Proto\Core\UserRelationProfile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserProfile($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akaxin\Proto\Core\UserRelationProfile::class);
        $this->user_profile = $arr;

        return $this;
    }

}

