<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_friend_relations.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *获取某用户与其他用户的好友关系
 *----
 *接口名
 *----
 * /hai/friend/relations
 *错误码
 *----
 *- success
 *- error.alert
 *
 * 
 */
class HaiFriendRelationsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 
     */
    private $site_user_id = '';
    /**
     *需要查询关系的用户ID
     *
     * 
     */
    private $target_site_user_id;

    public function __construct() {
        \GPBMetadata\Plugin\HaiFriendRelations::initOnce();
        parent::__construct();
    }

    /**
     * 
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->site_user_id;
    }

    /**
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_user_id = $var;

        return $this;
    }

    /**
     *需要查询关系的用户ID
     *
     * 
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTargetSiteUserId()
    {
        return $this->target_site_user_id;
    }

    /**
     *需要查询关系的用户ID
     *
     * 
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTargetSiteUserId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->target_site_user_id = $arr;

        return $this;
    }

}

