<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_checkMember.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 
 */
class HaiGroupCheckMemberResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * 请求在这个群里的成员( 肯定是request参数的子集 )
     *
     * 
     */
    private $members_site_user_id;

    public function __construct() {
        \GPBMetadata\Plugin\HaiGroupCheckMember::initOnce();
        parent::__construct();
    }

    /**
     * 请求在这个群里的成员( 肯定是request参数的子集 )
     *
     * 
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMembersSiteUserId()
    {
        return $this->members_site_user_id;
    }

    /**
     * 请求在这个群里的成员( 肯定是request参数的子集 )
     *
     * 
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMembersSiteUserId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->members_site_user_id = $arr;

        return $this;
    }

}

