<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_nonmembers.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 
 */
class HaiGroupNonmembersResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *群组成员信息
     *
     * 
     */
    private $group_member;
    /**
     * 分页总数
     *
     * 
     */
    private $page_total_num = 0;

    public function __construct() {
        \GPBMetadata\Plugin\HaiGroupNonmembers::initOnce();
        parent::__construct();
    }

    /**
     *群组成员信息
     *
     * 
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroupMember()
    {
        return $this->group_member;
    }

    /**
     *群组成员信息
     *
     * 
     * @param \Akaxin\Proto\Core\GroupMemberProfile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroupMember($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akaxin\Proto\Core\GroupMemberProfile::class);
        $this->group_member = $arr;

        return $this;
    }

    /**
     * 分页总数
     *
     * 
     * @return int
     */
    public function getPageTotalNum()
    {
        return $this->page_total_num;
    }

    /**
     * 分页总数
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setPageTotalNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_total_num = $var;

        return $this;
    }

}

