<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_addMember.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *向群里添加群成员
 *----
 *> 如果此人已在群里，返回成功而不是失败
 *接口名
 *----
 * /hai/group/addMember
 *错误码
 *----
 *- success
 *- error.alert
 *
 * 
 */
class HaiGroupAddMemberRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *群组ID
     *
     * 
     */
    private $group_id = '';
    /**
     *群组中需要增加的用户ID
     *
     * 
     */
    private $member_site_user_id;

    public function __construct() {
        \GPBMetadata\Plugin\HaiGroupAddMember::initOnce();
        parent::__construct();
    }

    /**
     *群组ID
     *
     * 
     * @return string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     *群组ID
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_id = $var;

        return $this;
    }

    /**
     *群组中需要增加的用户ID
     *
     * 
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMemberSiteUserId()
    {
        return $this->member_site_user_id;
    }

    /**
     *群组中需要增加的用户ID
     *
     * 
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMemberSiteUserId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->member_site_user_id = $arr;

        return $this;
    }

}

