<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_profile.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 
 */
class HaiGroupProfileResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *群组资料页信息
     *
     * 
     */
    private $profile = null;

    public function __construct() {
        \GPBMetadata\Plugin\HaiGroupProfile::initOnce();
        parent::__construct();
    }

    /**
     *群组资料页信息
     *
     * 
     * @return \Akaxin\Proto\Core\GroupProfile
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     *群组资料页信息
     *
     * 
     * @param \Akaxin\Proto\Core\GroupProfile $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\GroupProfile::class);
        $this->profile = $var;

        return $this;
    }

}

