<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_list.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 
 */
class HaiGroupListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *用户的群列表
     *
     * 
     */
    private $group_profile;
    /**
     * 一共多少页
     *
     * 
     */
    private $page_total_num = 0;

    public function __construct() {
        \GPBMetadata\Plugin\HaiGroupList::initOnce();
        parent::__construct();
    }

    /**
     *用户的群列表
     *
     * 
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroupProfile()
    {
        return $this->group_profile;
    }

    /**
     *用户的群列表
     *
     * 
     * @param \Akaxin\Proto\Core\SimpleGroupProfile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroupProfile($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akaxin\Proto\Core\SimpleGroupProfile::class);
        $this->group_profile = $arr;

        return $this;
    }

    /**
     * 一共多少页
     *
     * 
     * @return int
     */
    public function getPageTotalNum()
    {
        return $this->page_total_num;
    }

    /**
     * 一共多少页
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setPageTotalNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_total_num = $var;

        return $this;
    }

}

