<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_update.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *更新群资料
 *----
 *接口名
 *----
 * /hai/group/update
 *错误码
 *----
 *- success
 *- error.alert
 *
 * 
 */
class HaiGroupUpdateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 显示的设置群组ID
     *
     * 
     */
    private $group_id = '';
    /**
     *需要更新的群组资料
     *
     * 
     */
    private $profile = null;

    public function __construct() {
        \GPBMetadata\Plugin\HaiGroupUpdate::initOnce();
        parent::__construct();
    }

    /**
     * 显示的设置群组ID
     *
     * 
     * @return string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * 显示的设置群组ID
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_id = $var;

        return $this;
    }

    /**
     *需要更新的群组资料
     *
     * 
     * @return \Akaxin\Proto\Core\GroupProfile
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     *需要更新的群组资料
     *
     * 
     * @param \Akaxin\Proto\Core\GroupProfile $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\GroupProfile::class);
        $this->profile = $var;

        return $this;
    }

}

