<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_delete.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *删除群组
 *----
 *接口名
 *----
 * /hai/group/delete
 *错误码
 *----
 *- success
 *- error.alert
 *
 * 
 */
class HaiGroupDeleteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *删除的群组ID
     *
     * 
     */
    private $group_id = '';

    public function __construct() {
        \GPBMetadata\Plugin\HaiGroupDelete::initOnce();
        parent::__construct();
    }

    /**
     *删除的群组ID
     *
     * 
     * @return string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     *删除的群组ID
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_id = $var;

        return $this;
    }

}

