<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_nonmembers.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *分页获非群成员
 *----
 *接口名
 *----
 * /hai/group/nonmembers
 *错误码
 *----
 *- success
 *- error.alert
 *
 * 
 */
class HaiGroupNonmembersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 以谁的视角获取这份数据
     *
     * 
     */
    private $site_user_id = '';
    /**
     *群组ID
     *
     * 
     */
    private $group_id = '';
    /**
     *分页：第几页
     *
     * 
     */
    private $page_number = 0;
    /**
     *分页：每页条数，默认100
     *
     * 
     */
    private $page_size = 0;

    public function __construct() {
        \GPBMetadata\Plugin\HaiGroupNonmembers::initOnce();
        parent::__construct();
    }

    /**
     * 以谁的视角获取这份数据
     *
     * 
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->site_user_id;
    }

    /**
     * 以谁的视角获取这份数据
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_user_id = $var;

        return $this;
    }

    /**
     *群组ID
     *
     * 
     * @return string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     *群组ID
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_id = $var;

        return $this;
    }

    /**
     *分页：第几页
     *
     * 
     * @return int
     */
    public function getPageNumber()
    {
        return $this->page_number;
    }

    /**
     *分页：第几页
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setPageNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_number = $var;

        return $this;
    }

    /**
     *分页：每页条数，默认100
     *
     * 
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     *分页：每页条数，默认100
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

}

