<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_updateProfile.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.HaiGroupUpdateProfileRequest</code>
 */
class HaiGroupUpdateProfileRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *需要更新的群组资料
     *
     * Generated from protobuf field <code>.core.GroupProfile profile = 1;</code>
     */
    private $profile = null;

    public function __construct() {
        \GPBMetadata\Plugin\HaiGroupUpdateProfile::initOnce();
        parent::__construct();
    }

    /**
     *需要更新的群组资料
     *
     * Generated from protobuf field <code>.core.GroupProfile profile = 1;</code>
     * @return \Akaxin\Proto\Core\GroupProfile
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     *需要更新的群组资料
     *
     * Generated from protobuf field <code>.core.GroupProfile profile = 1;</code>
     * @param \Akaxin\Proto\Core\GroupProfile $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\GroupProfile::class);
        $this->profile = $var;

        return $this;
    }

}

