<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_message_proxy.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *代发消息
 *----
 *接口名
 *----
 * /hai/message/proxy
 *错误码
 *----
 *- success
 *- error.alert
 *
 * 
 */
class HaiMessageProxyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *代理发送的消息请求
     *
     * 
     */
    private $proxy_msg = null;

    public function __construct() {
        \GPBMetadata\Plugin\HaiMessageProxy::initOnce();
        parent::__construct();
    }

    /**
     *代理发送的消息请求
     *
     * 
     * @return \Akaxin\Proto\Site\ImCtsMessageRequest
     */
    public function getProxyMsg()
    {
        return $this->proxy_msg;
    }

    /**
     *代理发送的消息请求
     *
     * 
     * @param \Akaxin\Proto\Site\ImCtsMessageRequest $var
     * @return $this
     */
    public function setProxyMsg($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Site\ImCtsMessageRequest::class);
        $this->proxy_msg = $var;

        return $this;
    }

}

