<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_message_proxy.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.HaiMessageProxyRequest</code>
 */
class HaiMessageProxyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *代理发送的消息请求
     *
     * Generated from protobuf field <code>.site.ImCtsMessageRequest proxy_msg = 1;</code>
     */
    private $proxy_msg = null;

    public function __construct() {
        \GPBMetadata\Plugin\HaiMessageProxy::initOnce();
        parent::__construct();
    }

    /**
     *代理发送的消息请求
     *
     * Generated from protobuf field <code>.site.ImCtsMessageRequest proxy_msg = 1;</code>
     * @return \Site\ImCtsMessageRequest
     */
    public function getProxyMsg()
    {
        return $this->proxy_msg;
    }

    /**
     *代理发送的消息请求
     *
     * Generated from protobuf field <code>.site.ImCtsMessageRequest proxy_msg = 1;</code>
     * @param \Site\ImCtsMessageRequest $var
     * @return $this
     */
    public function setProxyMsg($var)
    {
        GPBUtil::checkMessage($var, \Site\ImCtsMessageRequest::class);
        $this->proxy_msg = $var;

        return $this;
    }

}

