<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_push_notices.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *全员发送通知
 *
 * Generated from protobuf message <code>plugin.HaiPushNoticesRequest</code>
 */
class HaiPushNoticesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *push通知的title(副标题)，客户端主标题展示站点名称
     *
     * Generated from protobuf field <code>string subtitle = 1;</code>
     */
    private $subtitle = '';
    /**
     *通知的内容
     *
     * Generated from protobuf field <code>string content = 2;</code>
     */
    private $content = '';
    /**
     *通知的跳转
     *
     * Generated from protobuf field <code>string push_goto = 3;</code>
     */
    private $push_goto = '';

    public function __construct() {
        \GPBMetadata\Plugin\HaiPushNotices::initOnce();
        parent::__construct();
    }

    /**
     *push通知的title(副标题)，客户端主标题展示站点名称
     *
     * Generated from protobuf field <code>string subtitle = 1;</code>
     * @return string
     */
    public function getSubtitle()
    {
        return $this->subtitle;
    }

    /**
     *push通知的title(副标题)，客户端主标题展示站点名称
     *
     * Generated from protobuf field <code>string subtitle = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->subtitle = $var;

        return $this;
    }

    /**
     *通知的内容
     *
     * Generated from protobuf field <code>string content = 2;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     *通知的内容
     *
     * Generated from protobuf field <code>string content = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     *通知的跳转
     *
     * Generated from protobuf field <code>string push_goto = 3;</code>
     * @return string
     */
    public function getPushGoto()
    {
        return $this->push_goto;
    }

    /**
     *通知的跳转
     *
     * Generated from protobuf field <code>string push_goto = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPushGoto($var)
    {
        GPBUtil::checkString($var, True);
        $this->push_goto = $var;

        return $this;
    }

}

