<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_plugin_delete.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.HaiPluginDeleteResponse</code>
 */
class HaiPluginDeleteResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Plugin\HaiPluginDelete::initOnce();
        parent::__construct();
    }

}

