<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_session_profile.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *通过用户session获取用户资料
 *----
 *接口名
 *----
 * /hai/session/profile
 *错误码
 *----
 * success
 * error.alert
 *
 * 
 */
class HaiSessionProfileRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *用户的sessionid，base64_safe_url
     *
     * 
     */
    private $base64_safe_url_session_id = '';

    public function __construct() {
        \GPBMetadata\Plugin\HaiSessionProfile::initOnce();
        parent::__construct();
    }

    /**
     *用户的sessionid，base64_safe_url
     *
     * 
     * @return string
     */
    public function getBase64SafeUrlSessionId()
    {
        return $this->base64_safe_url_session_id;
    }

    /**
     *用户的sessionid，base64_safe_url
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setBase64SafeUrlSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->base64_safe_url_session_id = $var;

        return $this;
    }

}

