<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_site_getConfig.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 
 */
class HaiSiteGetConfigResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *信息配置，Key为SiteConfigKey
     *
     * 
     */
    private $site_config = null;

    public function __construct() {
        \GPBMetadata\Plugin\HaiSiteGetConfig::initOnce();
        parent::__construct();
    }

    /**
     *信息配置，Key为SiteConfigKey
     *
     * 
     * @return \Akaxin\Proto\Core\SiteBackConfig
     */
    public function getSiteConfig()
    {
        return $this->site_config;
    }

    /**
     *信息配置，Key为SiteConfigKey
     *
     * 
     * @param \Akaxin\Proto\Core\SiteBackConfig $var
     * @return $this
     */
    public function setSiteConfig($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\SiteBackConfig::class);
        $this->site_config = $var;

        return $this;
    }

}

