<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_site_getConfig.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *获取站点的配置
 *----
 *接口名
 *----
 * /hai/site/getConfig
 *错误码
 *----
 *- success
 *- error.alert
 *
 * 
 */
class HaiSiteGetConfigRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Plugin\HaiSiteGetConfig::initOnce();
        parent::__construct();
    }

}

