<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_list.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *获取站点上用户
 *----
 *接口名
 *----
 * /hai/user/list
 *错误码
 *----
 *- success
 *- error.alert
 *
 * 
 */
class HaiUserListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *分页：第几页
     *
     * 
     */
    private $page_number = 0;
    /**
     *分页：每页条数
     *
     * 
     */
    private $page_size = 0;

    public function __construct() {
        \GPBMetadata\Plugin\HaiUserList::initOnce();
        parent::__construct();
    }

    /**
     *分页：第几页
     *
     * 
     * @return int
     */
    public function getPageNumber()
    {
        return $this->page_number;
    }

    /**
     *分页：第几页
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setPageNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_number = $var;

        return $this;
    }

    /**
     *分页：每页条数
     *
     * 
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     *分页：每页条数
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

}

