<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_update.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *更新用户信息
 *----
 *接口名
 *----
 * /hai/user/update
 *错误码
 *----
 *- success
 *- error.alert
 *
 * 
 */
class HaiUserUpdateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *需要更新的用户信息
     *
     * 
     */
    private $user_profile = null;

    public function __construct() {
        \GPBMetadata\Plugin\HaiUserUpdate::initOnce();
        parent::__construct();
    }

    /**
     *需要更新的用户信息
     *
     * 
     * @return \Akaxin\Proto\Core\UserProfile
     */
    public function getUserProfile()
    {
        return $this->user_profile;
    }

    /**
     *需要更新的用户信息
     *
     * 
     * @param \Akaxin\Proto\Core\UserProfile $var
     * @return $this
     */
    public function setUserProfile($var)
    {
        GPBUtil::checkMessage($var, \Akaxin\Proto\Core\UserProfile::class);
        $this->user_profile = $var;

        return $this;
    }

}

