<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_avatar.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 
 */
class HaiUserAvatarResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *图片二进制内容
     *
     * 
     */
    private $photo_content = '';

    public function __construct() {
        \GPBMetadata\Plugin\HaiUserAvatar::initOnce();
        parent::__construct();
    }

    /**
     *图片二进制内容
     *
     * 
     * @return string
     */
    public function getPhotoContent()
    {
        return $this->photo_content;
    }

    /**
     *图片二进制内容
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setPhotoContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->photo_content = $var;

        return $this;
    }

}

