<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_friends.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 
 */
class HaiUserFriendsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *需要查找的用户
     *
     * 
     */
    private $profile;
    /**
     *总页数
     *
     * 
     */
    private $page_total_num = 0;

    public function __construct() {
        \GPBMetadata\Plugin\HaiUserFriends::initOnce();
        parent::__construct();
    }

    /**
     *需要查找的用户
     *
     * 
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     *需要查找的用户
     *
     * 
     * @param \Akaxin\Proto\Core\SimpleUserProfile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProfile($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akaxin\Proto\Core\SimpleUserProfile::class);
        $this->profile = $arr;

        return $this;
    }

    /**
     *总页数
     *
     * 
     * @return int
     */
    public function getPageTotalNum()
    {
        return $this->page_total_num;
    }

    /**
     *总页数
     *
     * 
     * @param int $var
     * @return $this
     */
    public function setPageTotalNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_total_num = $var;

        return $this;
    }

}

