<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_profile.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 *获取用户资料
 *----
 *接口名
 *----
 * /hai/user/profile
 *错误码
 *----
 *- success
 *- error.alert
 *
 * 
 */
class HaiUserProfileRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *需要查找的用户ID
     *
     * 
     */
    private $site_user_id = '';

    public function __construct() {
        \GPBMetadata\Plugin\HaiUserProfile::initOnce();
        parent::__construct();
    }

    /**
     *需要查找的用户ID
     *
     * 
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->site_user_id;
    }

    /**
     *需要查找的用户ID
     *
     * 
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_user_id = $var;

        return $this;
    }

}

