<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_list.proto

namespace Akaxin\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 
 */
class HaiUserListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *查询的结果
     *
     * 
     */
    private $user_profile;
    /**
     * 
     */
    private $page_total_num = 0;

    public function __construct() {
        \GPBMetadata\Plugin\HaiUserList::initOnce();
        parent::__construct();
    }

    /**
     *查询的结果
     *
     * 
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserProfile()
    {
        return $this->user_profile;
    }

    /**
     *查询的结果
     *
     * 
     * @param \Akaxin\Proto\Core\SimpleUserProfile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserProfile($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akaxin\Proto\Core\SimpleUserProfile::class);
        $this->user_profile = $arr;

        return $this;
    }

    /**
     * 
     * @return int
     */
    public function getPageTotalNum()
    {
        return $this->page_total_num;
    }

    /**
     * 
     * @param int $var
     * @return $this
     */
    public function setPageTotalNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_total_num = $var;

        return $this;
    }

}

